import type { DndSpellPreset } from "./schema";

function p(partial: Partial<DndSpellPreset> & { id: string; name: string; level: number }): DndSpellPreset {
  return {
    prepared: false,
    school: "",
    castingTime: "1 个动作",
    range: "60 尺",
    duration: "即效",
    effect: "",
    concentration: false,
    ritual: false,
    v: true,
    s: true,
    m: false,
    materials: "",
    hasAttack: false,
    saveAbility: "",
    dmgCount: 0,
    dmgFaces: 6,
    dmgBonus: 0,
    dmgType: "",
    ...partial,
  };
}

/** 世界尚未自建法术表时的推荐列表（2024 简中常用） */
export const DEFAULT_SPELL_PRESETS: DndSpellPreset[] = [
  p({
    id: "preset-fire-bolt",
    name: "火焰箭",
    level: 0,
    school: "塑能",
    range: "120 尺",
    hasAttack: true,
    dmgCount: 1,
    dmgFaces: 10,
    dmgType: "火焰",
    effect: "远程法术攻击。命中造成火焰伤害。",
  }),
  p({
    id: "preset-ray-of-frost",
    name: "冷冻射线",
    level: 0,
    school: "塑能",
    range: "60 尺",
    hasAttack: true,
    dmgCount: 1,
    dmgFaces: 8,
    dmgType: "冷冻",
    effect: "远程法术攻击。命中造成冷冻伤害，目标速度 −10 尺至你下回合开始。",
  }),
  p({
    id: "preset-shocking-grasp",
    name: "电爪",
    level: 0,
    school: "塑能",
    range: "触及",
    hasAttack: true,
    dmgCount: 1,
    dmgFaces: 8,
    dmgType: "闪电",
    effect: "近战法术攻击。命中造成闪电伤害，目标不能执行反应至其下回合开始。",
  }),
  p({
    id: "preset-sacred-flame",
    name: "圣火术",
    level: 0,
    school: "塑能",
    range: "60 尺",
    saveAbility: "dex",
    dmgCount: 1,
    dmgFaces: 8,
    dmgType: "光耀",
    effect: "目标做敏捷豁免，失败则受到光耀伤害。掩蔽不能使此豁免受益。",
  }),
  p({
    id: "preset-chill-touch",
    name: "颤栗之触",
    level: 0,
    school: "死灵",
    range: "120 尺",
    hasAttack: true,
    dmgCount: 1,
    dmgFaces: 8,
    dmgType: "黯蚀",
    effect: "远程法术攻击。命中造成黯蚀伤害，目标在你下回合开始前无法恢复生命。",
  }),
  p({
    id: "preset-magic-missile",
    name: "魔法飞弹",
    level: 1,
    school: "塑能",
    range: "120 尺",
    dmgCount: 3,
    dmgFaces: 4,
    dmgBonus: 3,
    dmgType: "力场",
    effect: "三枚飞镖自动命中，每枚 1d4+1 力场。可打同一或不同目标。",
  }),
  p({
    id: "preset-guiding-bolt",
    name: "光导箭",
    level: 1,
    school: "塑能",
    range: "120 尺",
    hasAttack: true,
    dmgCount: 4,
    dmgFaces: 6,
    dmgType: "光耀",
    effect: "远程法术攻击。命中造成光耀伤害，下一个打该目标的攻击具有优势（直至你下回合）。",
  }),
  p({
    id: "preset-inflict",
    name: "致伤术",
    level: 1,
    school: "死灵",
    range: "触及",
    hasAttack: true,
    dmgCount: 3,
    dmgFaces: 10,
    dmgType: "黯蚀",
    effect: "近战法术攻击。命中造成黯蚀伤害。",
  }),
  p({
    id: "preset-burning-hands",
    name: "燃烧之手",
    level: 1,
    school: "塑能",
    range: "自身（15 尺锥状）",
    saveAbility: "dex",
    dmgCount: 3,
    dmgFaces: 6,
    dmgType: "火焰",
    effect: "锥状内生物做敏捷豁免，失败受全部火焰伤害，成功减半。",
  }),
  p({
    id: "preset-scorching-ray",
    name: "灼热射线",
    level: 2,
    school: "塑能",
    range: "120 尺",
    hasAttack: true,
    dmgCount: 2,
    dmgFaces: 6,
    dmgType: "火焰",
    effect: "三条射线，各做一次远程法术攻击，命中 2d6 火焰。可打同一或不同目标。",
  }),
  p({
    id: "preset-fireball",
    name: "火球术",
    level: 3,
    school: "塑能",
    range: "150 尺",
    saveAbility: "dex",
    dmgCount: 8,
    dmgFaces: 6,
    dmgType: "火焰",
    effect: "20 尺半径内生物做敏捷豁免，失败受全部火焰伤害，成功减半。",
  }),
  p({
    id: "preset-lightning-bolt",
    name: "闪电束",
    level: 3,
    school: "塑能",
    range: "自身（100 尺线状）",
    saveAbility: "dex",
    dmgCount: 8,
    dmgFaces: 6,
    dmgType: "闪电",
    effect: "线状内生物做敏捷豁免，失败受全部闪电伤害，成功减半。",
  }),
  p({
    id: "preset-vampiric-touch",
    name: "吸血鬼之触",
    level: 3,
    school: "死灵",
    range: "自身",
    duration: "专注，至多 1 分钟",
    concentration: true,
    hasAttack: true,
    dmgCount: 3,
    dmgFaces: 6,
    dmgType: "黯蚀",
    effect: "近战法术攻击。命中造成黯蚀伤害，你恢复其中一半生命。",
  }),
];

export function spellFromPreset(preset: DndSpellPreset): DndSpellPreset {
  return {
    ...preset,
    id: crypto.randomUUID(),
    prepared: preset.level === 0,
  };
}
