import type { DndSpellPreset } from "./schema";

function p(partial: Partial<DndSpellPreset> & { id: string; name: string; level: number }): DndSpellPreset {
  return {
    prepared: false,
    school: "",
    castingTime: "1 个动作",
    range: "60 尺",
    duration: "即效",
    effect: "",
    concentration: false,
    ritual: false,
    v: true,
    s: true,
    m: false,
    materials: "",
    hasAttack: false,
    saveAbility: "",
    dmgCount: 0,
    dmgFaces: 6,
    dmgBonus: 0,
    dmgType: "",
    ...partial,
  };
}

/** 2024《玩家手册》核心法术（简中名）。机制摘要据 2024 规则，非完整原文。 */
export const DEFAULT_SPELL_PRESETS: DndSpellPreset[] = [
  p({ id: "preset-acid-splash", name: "酸液飞溅", level: 0, school: "塑能", saveAbility: "dex", dmgCount: 1, dmgType: "强酸", effect: "敏捷豁免。1d6强酸。5/11/17 级升骰。" }),
  p({ id: "preset-blade-ward", name: "剑刃防护", level: 0, school: "防护", range: "自身", duration: "专注，至多 1 分钟", concentration: true, effect: "专注。" }),
  p({ id: "preset-chill-touch", name: "颤栗之触", level: 0, school: "死灵", range: "触及", hasAttack: true, dmgCount: 1, dmgFaces: 10, dmgType: "黯蚀", effect: "近战法术攻击。1d10黯蚀。5/11/17 级升骰。" }),
  p({ id: "preset-dancing-lights", name: "舞光术", level: 0, school: "幻术", range: "120 尺", duration: "专注，至多 1 分钟", concentration: true, m: true, materials: "a bit of phosphorus", effect: "专注。" }),
  p({ id: "preset-druidcraft", name: "德鲁伊伎俩", level: 0, school: "变化", range: "30 尺", effect: "见规则书。" }),
  p({ id: "preset-eldritch-blast", name: "魔能爆", level: 0, school: "塑能", range: "120 尺", hasAttack: true, dmgCount: 1, dmgFaces: 10, dmgType: "力场", effect: "远程法术攻击。1d10力场。5/11/17 级额外射线。" }),
  p({ id: "preset-elementalism", name: "四象法门", level: 0, school: "变化", range: "30 尺", effect: "见规则书。" }),
  p({ id: "preset-fire-bolt", name: "火焰箭", level: 0, school: "塑能", range: "120 尺", hasAttack: true, dmgCount: 1, dmgFaces: 10, dmgType: "火焰", effect: "远程法术攻击。1d10火焰。5/11/17 级升骰。" }),
  p({ id: "preset-friends", name: "交友术", level: 0, school: "惑控", range: "10 尺", duration: "专注，至多 1 分钟", concentration: true, v: false, m: true, materials: "some makeup", saveAbility: "wis", effect: "专注。感知豁免。" }),
  p({ id: "preset-guidance", name: "神导术", level: 0, school: "预言", range: "触及", duration: "专注，至多 1 分钟", concentration: true, effect: "专注。" }),
  p({ id: "preset-light", name: "光亮术", level: 0, school: "塑能", range: "触及", duration: "1 小时", s: false, m: true, materials: "a firefly or phosphorescent moss", effect: "见规则书。" }),
  p({ id: "preset-mage-hand", name: "法师之手", level: 0, school: "咒法", range: "30 尺", duration: "1 分钟", effect: "见规则书。" }),
  p({ id: "preset-mending", name: "修复术", level: 0, school: "变化", castingTime: "1 分钟", range: "触及", m: true, materials: "two lodestones", effect: "见规则书。" }),
  p({ id: "preset-message", name: "传讯术", level: 0, school: "变化", range: "120 尺", duration: "1 轮", v: false, m: true, materials: "a copper wire", effect: "见规则书。" }),
  p({ id: "preset-mind-sliver", name: "心灵之楔", level: 0, school: "惑控", s: false, saveAbility: "int", dmgCount: 1, dmgType: "心灵", effect: "智力豁免。1d6心灵。5/11/17 级升骰。" }),
  p({ id: "preset-minor-illusion", name: "次级幻象", level: 0, school: "幻术", range: "30 尺", duration: "1 分钟", v: false, m: true, materials: "a bit of fleece", effect: "见规则书。" }),
  p({ id: "preset-poison-spray", name: "毒气喷涌", level: 0, school: "死灵", range: "30 尺", hasAttack: true, dmgCount: 1, dmgFaces: 12, dmgType: "毒素", effect: "远程法术攻击。1d12毒素。5/11/17 级升骰。" }),
  p({ id: "preset-prestidigitation", name: "魔法伎俩", level: 0, school: "变化", range: "10 尺", duration: "1 小时", effect: "见规则书。" }),
  p({ id: "preset-produce-flame", name: "燃火术", level: 0, school: "咒法", castingTime: "1 个附赠动作", range: "自身", duration: "10 分钟", hasAttack: true, dmgCount: 1, dmgFaces: 8, dmgType: "火焰", effect: "远程法术攻击。1d8火焰。5/11/17 级升骰。" }),
  p({ id: "preset-ray-of-frost", name: "冷冻射线", level: 0, school: "塑能", hasAttack: true, dmgCount: 1, dmgFaces: 8, dmgType: "冷冻", effect: "远程法术攻击。1d8冷冻。5/11/17 级升骰。" }),
  p({ id: "preset-resistance", name: "抵抗术", level: 0, school: "防护", range: "触及", duration: "专注，至多 1 分钟", concentration: true, effect: "专注。" }),
  p({ id: "preset-sacred-flame", name: "圣火术", level: 0, school: "塑能", saveAbility: "dex", dmgCount: 1, dmgFaces: 8, dmgType: "光耀", effect: "敏捷豁免。1d8光耀。5/11/17 级升骰。" }),
  p({ id: "preset-shillelagh", name: "橡棍术", level: 0, school: "变化", castingTime: "1 个附赠动作", range: "自身", duration: "1 分钟", m: true, materials: "mistletoe", dmgCount: 1, dmgFaces: 8, dmgType: "力场", effect: "1d8力场。5/11/17 级升骰。" }),
  p({ id: "preset-shocking-grasp", name: "电爪", level: 0, school: "塑能", range: "触及", hasAttack: true, dmgCount: 1, dmgFaces: 8, dmgType: "闪电", effect: "近战法术攻击。1d8闪电。5/11/17 级升骰。" }),
  p({ id: "preset-sorcerous-burst", name: "术法爆发", level: 0, school: "塑能", range: "120 尺", hasAttack: true, dmgCount: 1, dmgFaces: 8, dmgType: "自选", effect: "远程法术攻击。1d8自选。5/11/17 级升骰。" }),
  p({ id: "preset-spare-the-dying", name: "维生术", level: 0, school: "死灵", range: "15 尺", effect: "见规则书。" }),
  p({ id: "preset-starry-wisp", name: "点点星芒", level: 0, school: "塑能", hasAttack: true, dmgCount: 1, dmgFaces: 8, dmgType: "光耀", effect: "远程法术攻击。1d8光耀。5/11/17 级升骰。" }),
  p({ id: "preset-thaumaturgy", name: "奇术", level: 0, school: "变化", range: "30 尺", duration: "1 分钟", s: false, effect: "见规则书。" }),
  p({ id: "preset-thorn-whip", name: "荆棘之鞭", level: 0, school: "变化", range: "30 尺", m: true, materials: "the stem of a plant with thorns", hasAttack: true, dmgCount: 1, dmgType: "穿刺", effect: "近战法术攻击。1d6穿刺。5/11/17 级升骰。" }),
  p({ id: "preset-thunderclap", name: "鸣雷破", level: 0, school: "塑能", range: "自身（5 尺光环）", v: false, saveAbility: "con", dmgCount: 1, dmgType: "雷鸣", effect: "体质豁免。1d6雷鸣。5/11/17 级升骰。" }),
  p({ id: "preset-toll-the-dead", name: "亡者丧钟", level: 0, school: "死灵", saveAbility: "wis", dmgCount: 1, dmgFaces: 8, dmgType: "黯蚀", effect: "感知豁免。1d8黯蚀。5/11/17 级升骰。" }),
  p({ id: "preset-true-strike", name: "克敌先击", level: 0, school: "预言", range: "自身", v: false, m: true, materials: "a weapon with which you have proficiency and that is worth 1+ CP", effect: "5/11/17 级升骰。" }),
  p({ id: "preset-vicious-mockery", name: "恶毒嘲笑", level: 0, school: "惑控", s: false, saveAbility: "wis", dmgCount: 1, dmgType: "心灵", effect: "感知豁免。1d6心灵。5/11/17 级升骰。" }),
  p({ id: "preset-word-of-radiance", name: "光耀祷词", level: 0, school: "塑能", range: "自身（5 尺光环）", s: false, m: true, materials: "a sunburst token", saveAbility: "con", dmgCount: 1, dmgType: "光耀", effect: "体质豁免。1d6光耀。5/11/17 级升骰。" }),
  p({ id: "preset-alarm", name: "警报术", level: 1, school: "防护", castingTime: "1 分钟", range: "30 尺", duration: "8 小时", ritual: true, m: true, materials: "a bell and silver wire", effect: "仪式。" }),
  p({ id: "preset-animal-friendship", name: "化兽为友", level: 1, school: "惑控", range: "30 尺", duration: "24 小时", m: true, materials: "a morsel of food", saveAbility: "wis", effect: "感知豁免。升环增强。" }),
  p({ id: "preset-armor-of-agathys", name: "黯冰狱铠", level: 1, school: "防护", castingTime: "1 个附赠动作", range: "自身", duration: "1 小时", m: true, materials: "a shard of blue glass", effect: "升环增强。" }),
  p({ id: "preset-arms-of-hadar", name: "哈达之臂", level: 1, school: "咒法", range: "自身（10 尺光环）", saveAbility: "str", dmgCount: 2, dmgType: "黯蚀", effect: "力量豁免。2d6黯蚀。成功减半。升环增强。" }),
  p({ id: "preset-bane", name: "灾祸术", level: 1, school: "惑控", range: "30 尺", duration: "专注，至多 1 分钟", concentration: true, m: true, materials: "a drop of blood", saveAbility: "cha", effect: "专注。魅力豁免。升环增强。" }),
  p({ id: "preset-bless", name: "祝福术", level: 1, school: "惑控", range: "30 尺", duration: "专注，至多 1 分钟", concentration: true, m: true, materials: "a Holy Symbol worth 5+ GP", effect: "专注。升环增强。" }),
  p({ id: "preset-burning-hands", name: "燃烧之手", level: 1, school: "塑能", range: "自身（15 尺锥状）", saveAbility: "dex", dmgCount: 3, dmgType: "火焰", effect: "敏捷豁免。3d6火焰。成功减半。升环增强。" }),
  p({ id: "preset-charm-person", name: "魅惑类人", level: 1, school: "惑控", range: "30 尺", duration: "1 小时", saveAbility: "wis", effect: "感知豁免。升环增强。" }),
  p({ id: "preset-chromatic-orb", name: "繁彩球", level: 1, school: "塑能", range: "90 尺", m: true, materials: "a diamond worth 50+ GP", hasAttack: true, dmgCount: 3, dmgFaces: 8, dmgType: "自选", effect: "远程法术攻击。3d8自选。升环增强。" }),
  p({ id: "preset-color-spray", name: "七彩喷射", level: 1, school: "幻术", range: "自身（15 尺锥状）", m: true, materials: "a pinch of colorful sand", saveAbility: "con", effect: "体质豁免。" }),
  p({ id: "preset-command", name: "命令术", level: 1, school: "惑控", s: false, saveAbility: "wis", effect: "感知豁免。升环增强。" }),
  p({ id: "preset-compelled-duel", name: "强令对决", level: 1, school: "惑控", castingTime: "1 个附赠动作", range: "30 尺", duration: "专注，至多 1 分钟", concentration: true, s: false, saveAbility: "wis", effect: "专注。感知豁免。" }),
  p({ id: "preset-comprehend-languages", name: "通晓语言", level: 1, school: "预言", range: "自身", duration: "1 小时", ritual: true, m: true, materials: "a pinch of soot and salt", effect: "仪式。" }),
  p({ id: "preset-create-or-destroy-water", name: "造水术/枯水术", level: 1, school: "变化", range: "30 尺", m: true, materials: "a mix of water and sand", effect: "升环增强。" }),
  p({ id: "preset-cure-wounds", name: "疗伤术", level: 1, school: "防护", range: "触及", dmgCount: 2, dmgFaces: 8, dmgType: "治疗", effect: "恢复 2d8+调整值 生命。升环增强。" }),
  p({ id: "preset-detect-evil-and-good", name: "侦测善恶", level: 1, school: "预言", range: "自身（30 尺球状）", duration: "专注，至多 10 分钟", concentration: true, effect: "专注。" }),
  p({ id: "preset-detect-magic", name: "侦测魔法", level: 1, school: "预言", range: "自身（30 尺球状）", duration: "专注，至多 10 分钟", concentration: true, ritual: true, effect: "仪式。专注。" }),
  p({ id: "preset-detect-poison-and-disease", name: "侦测毒性和疾病", level: 1, school: "预言", range: "自身（30 尺球状）", duration: "专注，至多 10 分钟", concentration: true, ritual: true, m: true, materials: "a yew leaf", effect: "仪式。专注。" }),
  p({ id: "preset-disguise-self", name: "易容术", level: 1, school: "幻术", range: "自身", duration: "1 小时", effect: "见规则书。" }),
  p({ id: "preset-dissonant-whispers", name: "不谐低语", level: 1, school: "惑控", s: false, saveAbility: "wis", dmgCount: 3, dmgType: "心灵", effect: "感知豁免。3d6心灵。成功减半。升环增强。" }),
  p({ id: "preset-divine-favor", name: "神恩", level: 1, school: "变化", castingTime: "1 个附赠动作", range: "自身", duration: "1 分钟", dmgCount: 1, dmgFaces: 4, dmgType: "光耀", effect: "1d4光耀。" }),
  p({ id: "preset-divine-smite", name: "至圣斩", level: 1, school: "塑能", castingTime: "1 个附赠动作", range: "自身", s: false, dmgCount: 2, dmgFaces: 8, dmgType: "光耀", effect: "2d8光耀。升环增强。" }),
  p({ id: "preset-ensnaring-strike", name: "诱捕打击", level: 1, school: "咒法", castingTime: "1 个附赠动作", range: "自身", duration: "专注，至多 1 分钟", concentration: true, s: false, saveAbility: "str", dmgCount: 1, dmgType: "穿刺", effect: "专注。力量豁免。1d6穿刺。升环增强。" }),
  p({ id: "preset-entangle", name: "纠缠术", level: 1, school: "咒法", range: "90 尺", duration: "专注，至多 1 分钟", concentration: true, saveAbility: "str", effect: "专注。力量豁免。" }),
  p({ id: "preset-expeditious-retreat", name: "脚底抹油", level: 1, school: "变化", castingTime: "1 个附赠动作", range: "自身", duration: "专注，至多 10 分钟", concentration: true, effect: "专注。" }),
  p({ id: "preset-faerie-fire", name: "妖火", level: 1, school: "塑能", duration: "专注，至多 1 分钟", concentration: true, s: false, saveAbility: "dex", effect: "专注。敏捷豁免。" }),
  p({ id: "preset-false-life", name: "虚假生命", level: 1, school: "死灵", range: "自身", m: true, materials: "a drop of alcohol", effect: "升环增强。" }),
  p({ id: "preset-feather-fall", name: "羽落术", level: 1, school: "变化", castingTime: "1 个反应", duration: "1 分钟", s: false, m: true, materials: "a small feather or piece of down", effect: "见规则书。" }),
  p({ id: "preset-find-familiar", name: "寻获魔宠", level: 1, school: "咒法", castingTime: "1 小时", range: "10 尺", ritual: true, m: true, materials: "burning incense worth 10+ GP, which the spell consumes", effect: "仪式。" }),
  p({ id: "preset-fog-cloud", name: "云雾术", level: 1, school: "咒法", range: "120 尺", duration: "专注，至多 1 小时", concentration: true, effect: "专注。升环增强。" }),
  p({ id: "preset-goodberry", name: "神莓术", level: 1, school: "咒法", range: "触及", duration: "24 小时", m: true, materials: "a sprig of mistletoe", effect: "见规则书。" }),
  p({ id: "preset-grease", name: "油腻术", level: 1, school: "咒法", duration: "1 分钟", m: true, materials: "a bit of pork rind or butter", saveAbility: "dex", effect: "敏捷豁免。" }),
  p({ id: "preset-guiding-bolt", name: "光导箭", level: 1, school: "塑能", range: "120 尺", duration: "1 轮", hasAttack: true, dmgCount: 4, dmgType: "光耀", effect: "远程法术攻击。4d6光耀。升环增强。" }),
  p({ id: "preset-hail-of-thorns", name: "棘雹术", level: 1, school: "咒法", castingTime: "1 个附赠动作", range: "自身", s: false, saveAbility: "dex", dmgCount: 1, dmgFaces: 10, dmgType: "穿刺", effect: "敏捷豁免。1d10穿刺。成功减半。升环增强。" }),
  p({ id: "preset-healing-word", name: "治愈真言", level: 1, school: "防护", castingTime: "1 个附赠动作", s: false, dmgCount: 2, dmgFaces: 4, dmgType: "治疗", effect: "恢复 2d4+调整值 生命。升环增强。" }),
  p({ id: "preset-hellish-rebuke", name: "炼狱叱喝", level: 1, school: "塑能", castingTime: "1 个反应", saveAbility: "dex", dmgCount: 2, dmgFaces: 10, dmgType: "火焰", effect: "敏捷豁免。2d10火焰。成功减半。升环增强。" }),
  p({ id: "preset-heroism", name: "英雄气概", level: 1, school: "惑控", range: "触及", duration: "专注，至多 1 分钟", concentration: true, effect: "专注。升环增强。" }),
  p({ id: "preset-hex", name: "脆弱诅咒", level: 1, school: "惑控", castingTime: "1 个附赠动作", range: "90 尺", duration: "专注，至多 1 小时", concentration: true, m: true, materials: "the petrified eye of a newt", dmgCount: 1, dmgType: "黯蚀", effect: "专注。1d6黯蚀。升环增强。" }),
  p({ id: "preset-hunters-mark", name: "猎人印记", level: 1, school: "预言", castingTime: "1 个附赠动作", range: "90 尺", duration: "专注，至多 1 小时", concentration: true, s: false, dmgCount: 1, dmgType: "力场", effect: "专注。1d6力场。升环增强。" }),
  p({ id: "preset-ice-knife", name: "冰刃", level: 1, school: "咒法", v: false, m: true, materials: "a drop of water or a piece of ice", hasAttack: true, saveAbility: "dex", dmgCount: 1, dmgFaces: 10, dmgType: "自选", effect: "远程法术攻击。敏捷豁免。1d10自选。升环增强。" }),
  p({ id: "preset-identify", name: "鉴定术", level: 1, school: "预言", castingTime: "1 分钟", range: "触及", ritual: true, m: true, materials: "a pearl worth 100+ GP", effect: "仪式。" }),
  p({ id: "preset-illusory-script", name: "迷幻手稿", level: 1, school: "幻术", castingTime: "1 分钟", range: "触及", duration: "10 日", ritual: true, v: false, m: true, materials: "ink worth 10+ GP, which the spell consumes", effect: "仪式。" }),
  p({ id: "preset-inflict-wounds", name: "致伤术", level: 1, school: "死灵", range: "触及", saveAbility: "con", dmgCount: 2, dmgFaces: 10, dmgType: "黯蚀", effect: "体质豁免。2d10黯蚀。成功减半。升环增强。" }),
  p({ id: "preset-jump", name: "跳跃术", level: 1, school: "变化", castingTime: "1 个附赠动作", range: "触及", duration: "1 分钟", m: true, materials: "a grasshopper's hind leg", effect: "升环增强。" }),
  p({ id: "preset-longstrider", name: "大步奔行", level: 1, school: "变化", range: "触及", duration: "1 小时", m: true, materials: "a pinch of dirt", effect: "升环增强。" }),
  p({ id: "preset-mage-armor", name: "法师护甲", level: 1, school: "防护", range: "触及", duration: "8 小时", m: true, materials: "a piece of cured leather", effect: "见规则书。" }),
  p({ id: "preset-magic-missile", name: "魔法飞弹", level: 1, school: "塑能", range: "120 尺", dmgCount: 3, dmgFaces: 4, dmgBonus: 3, dmgType: "力场", effect: "3d4+3力场。升环增强。" }),
  p({ id: "preset-protection-from-evil-and-good", name: "防护善恶", level: 1, school: "防护", range: "触及", duration: "专注，至多 10 分钟", concentration: true, m: true, materials: "a flask of Holy Water worth 25+ GP, which the spell consumes", effect: "专注。" }),
  p({ id: "preset-purify-food-and-drink", name: "净化饮食", level: 1, school: "变化", range: "10 尺", ritual: true, effect: "仪式。" }),
  p({ id: "preset-ray-of-sickness", name: "致病射线", level: 1, school: "死灵", hasAttack: true, dmgCount: 2, dmgFaces: 8, dmgType: "毒素", effect: "远程法术攻击。2d8毒素。升环增强。" }),
  p({ id: "preset-sanctuary", name: "庇护术", level: 1, school: "防护", castingTime: "1 个附赠动作", range: "30 尺", duration: "1 分钟", m: true, materials: "a shard of glass from a mirror", saveAbility: "wis", effect: "感知豁免。" }),
  p({ id: "preset-searing-smite", name: "炽焰斩", level: 1, school: "塑能", castingTime: "1 个附赠动作", range: "自身", duration: "1 分钟", s: false, saveAbility: "con", dmgCount: 1, dmgType: "火焰", effect: "体质豁免。1d6火焰。升环增强。" }),
  p({ id: "preset-shield", name: "护盾术", level: 1, school: "防护", castingTime: "1 个反应", range: "自身", duration: "1 轮", effect: "见规则书。" }),
  p({ id: "preset-shield-of-faith", name: "虔诚护盾", level: 1, school: "防护", castingTime: "1 个附赠动作", duration: "专注，至多 10 分钟", concentration: true, m: true, materials: "a prayer scroll", effect: "专注。" }),
  p({ id: "preset-silent-image", name: "无声幻影", level: 1, school: "幻术", duration: "专注，至多 10 分钟", concentration: true, m: true, materials: "a bit of fleece", effect: "专注。" }),
  p({ id: "preset-sleep", name: "睡眠术", level: 1, school: "惑控", duration: "专注，至多 1 分钟", concentration: true, m: true, materials: "a pinch of sand or rose petals", saveAbility: "wis", effect: "专注。感知豁免。" }),
  p({ id: "preset-speak-with-animals", name: "动物交谈", level: 1, school: "预言", range: "自身", duration: "10 分钟", ritual: true, effect: "仪式。" }),
  p({ id: "preset-tashas-hideous-laughter", name: "塔莎狂笑术", level: 1, school: "惑控", range: "30 尺", duration: "专注，至多 1 分钟", concentration: true, m: true, materials: "a tart and a feather", saveAbility: "wis", effect: "专注。感知豁免。升环增强。" }),
  p({ id: "preset-tensers-floating-disk", name: "谭森浮碟术", level: 1, school: "咒法", range: "30 尺", duration: "1 小时", ritual: true, m: true, materials: "a drop of mercury", effect: "仪式。" }),
  p({ id: "preset-thunderous-smite", name: "雷鸣斩", level: 1, school: "塑能", castingTime: "1 个附赠动作", range: "自身", s: false, saveAbility: "str", dmgCount: 2, dmgType: "雷鸣", effect: "力量豁免。2d6雷鸣。升环增强。" }),
  p({ id: "preset-thunderwave", name: "雷鸣波", level: 1, school: "塑能", range: "自身（15 尺立方）", saveAbility: "con", dmgCount: 2, dmgFaces: 8, dmgType: "雷鸣", effect: "体质豁免。2d8雷鸣。成功减半。升环增强。" }),
  p({ id: "preset-unseen-servant", name: "隐形仆役", level: 1, school: "咒法", duration: "1 小时", ritual: true, m: true, materials: "a bit of string and of wood", effect: "仪式。" }),
  p({ id: "preset-witch-bolt", name: "巫术箭", level: 1, school: "塑能", duration: "专注，至多 1 分钟", concentration: true, m: true, materials: "a twig struck by lightning", hasAttack: true, dmgCount: 2, dmgFaces: 12, dmgType: "闪电", effect: "专注。远程法术攻击。2d12闪电。升环增强。" }),
  p({ id: "preset-wrathful-smite", name: "激愤斩", level: 1, school: "死灵", castingTime: "1 个附赠动作", range: "自身", duration: "1 分钟", s: false, saveAbility: "wis", dmgCount: 1, dmgType: "黯蚀", effect: "感知豁免。1d6黯蚀。升环增强。" }),
  p({ id: "preset-aid", name: "援助术", level: 2, school: "防护", range: "30 尺", duration: "8 小时", m: true, materials: "a strip of white cloth", effect: "升环增强。" }),
  p({ id: "preset-alter-self", name: "变身术", level: 2, school: "变化", range: "自身", duration: "专注，至多 1 小时", concentration: true, dmgCount: 1, dmgType: "自选", effect: "专注。1d6自选。" }),
  p({ id: "preset-animal-messenger", name: "动物信使", level: 2, school: "惑控", range: "30 尺", duration: "24 小时", ritual: true, m: true, materials: "a morsel of food", saveAbility: "cha", effect: "仪式。魅力豁免。升环增强。" }),
  p({ id: "preset-arcane-lock", name: "秘法锁", level: 2, school: "防护", range: "触及", duration: "直至解除", m: true, materials: "gold dust worth 25+ GP, which the spell consumes", effect: "见规则书。" }),
  p({ id: "preset-arcane-vigor", name: "复苏秘法", level: 2, school: "防护", castingTime: "1 个附赠动作", range: "自身", effect: "升环增强。" }),
  p({ id: "preset-augury", name: "卜筮术", level: 2, school: "预言", castingTime: "1 分钟", range: "自身", ritual: true, m: true, materials: "specially marked sticks, bones, cards, or other divinatory tokens worth 25+ GP", effect: "仪式。" }),
  p({ id: "preset-barkskin", name: "树肤术", level: 2, school: "变化", castingTime: "1 个附赠动作", range: "触及", duration: "1 小时", m: true, materials: "a handful of oak bark", effect: "见规则书。" }),
  p({ id: "preset-beast-sense", name: "野兽感官", level: 2, school: "预言", range: "触及", duration: "专注，至多 1 小时", concentration: true, ritual: true, v: false, effect: "仪式。专注。" }),
  p({ id: "preset-blindness-deafness", name: "目盲术/耳聋术", level: 2, school: "变化", range: "120 尺", duration: "1 分钟", s: false, saveAbility: "con", effect: "体质豁免。升环增强。" }),
  p({ id: "preset-blur", name: "朦胧术", level: 2, school: "幻术", range: "自身", duration: "专注，至多 1 分钟", concentration: true, s: false, effect: "专注。" }),
  p({ id: "preset-calm-emotions", name: "安定心神", level: 2, school: "惑控", duration: "专注，至多 1 分钟", concentration: true, saveAbility: "cha", effect: "专注。魅力豁免。" }),
  p({ id: "preset-cloud-of-daggers", name: "匕首之云", level: 2, school: "咒法", duration: "专注，至多 1 分钟", concentration: true, m: true, materials: "a sliver of glass", dmgCount: 4, dmgFaces: 4, dmgType: "挥砍", effect: "专注。4d4挥砍。升环增强。" }),
  p({ id: "preset-continual-flame", name: "不灭明焰", level: 2, school: "塑能", range: "触及", duration: "直至解除", m: true, materials: "ruby dust worth 50+ GP, which the spell consumes", effect: "见规则书。" }),
  p({ id: "preset-cordon-of-arrows", name: "警戒箭阵", level: 2, school: "变化", range: "触及", duration: "8 小时", m: true, materials: "four or more arrows or bolts", saveAbility: "dex", dmgCount: 2, dmgFaces: 4, dmgType: "穿刺", effect: "敏捷豁免。2d4穿刺。升环增强。" }),
  p({ id: "preset-crown-of-madness", name: "疯狂冠冕", level: 2, school: "惑控", range: "120 尺", duration: "专注，至多 1 分钟", concentration: true, saveAbility: "wis", effect: "专注。感知豁免。" }),
  p({ id: "preset-darkness", name: "黑暗术", level: 2, school: "塑能", duration: "专注，至多 10 分钟", concentration: true, s: false, m: true, materials: "bat fur and a piece of coal", effect: "专注。" }),
  p({ id: "preset-darkvision", name: "黑暗视觉", level: 2, school: "变化", range: "触及", duration: "8 小时", m: true, materials: "a dried carrot", effect: "见规则书。" }),
  p({ id: "preset-detect-thoughts", name: "侦测思想", level: 2, school: "预言", range: "自身", duration: "专注，至多 1 分钟", concentration: true, m: true, materials: "1 Copper Piece", saveAbility: "wis", effect: "专注。感知豁免。" }),
  p({ id: "preset-dragons-breath", name: "龙息术", level: 2, school: "变化", castingTime: "1 个附赠动作", range: "触及", duration: "专注，至多 1 分钟", concentration: true, m: true, materials: "a hot pepper", saveAbility: "dex", dmgCount: 3, dmgType: "自选", effect: "专注。敏捷豁免。3d6自选。成功减半。升环增强。" }),
  p({ id: "preset-enhance-ability", name: "强化属性", level: 2, school: "变化", range: "触及", duration: "专注，至多 1 小时", concentration: true, m: true, materials: "fur or a feather", effect: "专注。升环增强。" }),
  p({ id: "preset-enlarge-reduce", name: "变巨/缩小术", level: 2, school: "变化", range: "30 尺", duration: "专注，至多 1 分钟", concentration: true, m: true, materials: "a pinch of powdered iron", saveAbility: "con", effect: "专注。体质豁免。" }),
  p({ id: "preset-enthrall", name: "注目术", level: 2, school: "惑控", duration: "专注，至多 1 分钟", concentration: true, saveAbility: "wis", effect: "专注。感知豁免。" }),
  p({ id: "preset-find-steed", name: "寻获坐骑", level: 2, school: "咒法", range: "30 尺", effect: "升环增强。" }),
  p({ id: "preset-find-traps", name: "寻找陷阱", level: 2, school: "预言", range: "120 尺", effect: "见规则书。" }),
  p({ id: "preset-flame-blade", name: "火焰刀", level: 2, school: "塑能", castingTime: "1 个附赠动作", range: "自身", duration: "专注，至多 10 分钟", concentration: true, m: true, materials: "a sumac leaf", hasAttack: true, dmgCount: 3, dmgType: "火焰", effect: "专注。近战法术攻击。3d6火焰。升环增强。" }),
  p({ id: "preset-flaming-sphere", name: "炽焰法球", level: 2, school: "咒法", duration: "专注，至多 1 分钟", concentration: true, m: true, materials: "a ball of wax", saveAbility: "dex", dmgCount: 2, dmgType: "火焰", effect: "专注。敏捷豁免。2d6火焰。成功减半。升环增强。" }),
  p({ id: "preset-gentle-repose", name: "遗体防腐", level: 2, school: "死灵", range: "触及", duration: "10 日", ritual: true, m: true, materials: "2 Copper Pieces, which the spell consumes", effect: "仪式。" }),
  p({ id: "preset-gust-of-wind", name: "造风术", level: 2, school: "塑能", range: "自身", duration: "专注，至多 1 分钟", concentration: true, m: true, materials: "a legume seed", saveAbility: "str", effect: "专注。力量豁免。" }),
  p({ id: "preset-heat-metal", name: "灼热金属", level: 2, school: "变化", duration: "专注，至多 1 分钟", concentration: true, m: true, materials: "a piece of iron and a flame", saveAbility: "con", dmgCount: 2, dmgFaces: 8, dmgType: "火焰", effect: "专注。体质豁免。2d8火焰。升环增强。" }),
  p({ id: "preset-hold-person", name: "定身类人", level: 2, school: "惑控", duration: "专注，至多 1 分钟", concentration: true, m: true, materials: "a straight piece of iron", saveAbility: "wis", effect: "专注。感知豁免。升环增强。" }),
  p({ id: "preset-invisibility", name: "隐形术", level: 2, school: "幻术", range: "触及", duration: "专注，至多 1 小时", concentration: true, m: true, materials: "an eyelash in gum arabic", effect: "专注。升环增强。" }),
  p({ id: "preset-knock", name: "敲击术", level: 2, school: "变化", s: false, effect: "见规则书。" }),
  p({ id: "preset-lesser-restoration", name: "次等复原术", level: 2, school: "防护", castingTime: "1 个附赠动作", range: "触及", effect: "见规则书。" }),
  p({ id: "preset-levitate", name: "浮空术", level: 2, school: "变化", duration: "专注，至多 10 分钟", concentration: true, m: true, materials: "a metal spring", saveAbility: "con", effect: "专注。体质豁免。" }),
  p({ id: "preset-locate-animals-or-plants", name: "动植物定位术", level: 2, school: "预言", range: "自身", ritual: true, m: true, materials: "fur from a bloodhound", effect: "仪式。" }),
  p({ id: "preset-locate-object", name: "物件定位术", level: 2, school: "预言", range: "自身", duration: "专注，至多 10 分钟", concentration: true, m: true, materials: "a forked twig", effect: "专注。" }),
  p({ id: "preset-magic-mouth", name: "魔嘴术", level: 2, school: "幻术", castingTime: "1 分钟", range: "30 尺", duration: "直至解除", ritual: true, m: true, materials: "jade dust worth 10+ GP, which the spell consumes", effect: "仪式。" }),
  p({ id: "preset-magic-weapon", name: "魔化武器", level: 2, school: "变化", castingTime: "1 个附赠动作", range: "触及", duration: "1 小时", effect: "升环增强。" }),
  p({ id: "preset-melfs-acid-arrow", name: "马友夫强酸箭", level: 2, school: "塑能", range: "90 尺", m: true, materials: "powdered rhubarb leaf", hasAttack: true, dmgCount: 4, dmgFaces: 4, dmgType: "强酸", effect: "远程法术攻击。4d4强酸。升环增强。" }),
  p({ id: "preset-mind-spike", name: "心灵尖刺", level: 2, school: "预言", range: "120 尺", duration: "专注，至多 1 小时", concentration: true, v: false, saveAbility: "wis", dmgCount: 3, dmgFaces: 8, dmgType: "心灵", effect: "专注。感知豁免。3d8心灵。成功减半。升环增强。" }),
  p({ id: "preset-mirror-image", name: "镜影术", level: 2, school: "幻术", range: "自身", duration: "1 分钟", effect: "见规则书。" }),
  p({ id: "preset-misty-step", name: "迷踪步", level: 2, school: "咒法", castingTime: "1 个附赠动作", range: "自身", s: false, effect: "见规则书。" }),
  p({ id: "preset-moonbeam", name: "月华之光", level: 2, school: "塑能", range: "120 尺", duration: "专注，至多 1 分钟", concentration: true, m: true, materials: "a moonseed leaf", saveAbility: "con", dmgCount: 2, dmgFaces: 10, dmgType: "光耀", effect: "专注。体质豁免。2d10光耀。成功减半。升环增强。" }),
  p({ id: "preset-nystuls-magic-aura", name: "涅斯图魔法灵光", level: 2, school: "幻术", range: "触及", duration: "24 小时", m: true, materials: "a small square of silk", effect: "见规则书。" }),
  p({ id: "preset-pass-without-trace", name: "行动无踪", level: 2, school: "防护", range: "自身（30 尺光环）", duration: "专注，至多 1 小时", concentration: true, m: true, materials: "ashes from burned mistletoe", effect: "专注。" }),
  p({ id: "preset-phantasmal-force", name: "魅影之力", level: 2, school: "幻术", duration: "专注，至多 1 分钟", concentration: true, m: true, materials: "a bit of fleece", saveAbility: "int", dmgCount: 2, dmgFaces: 8, dmgType: "心灵", effect: "专注。智力豁免。2d8心灵。" }),
  p({ id: "preset-prayer-of-healing", name: "治疗祷言", level: 2, school: "防护", castingTime: "10 分钟", range: "30 尺", s: false, dmgCount: 2, dmgFaces: 8, dmgType: "治疗", effect: "恢复 2d8+调整值 生命。升环增强。" }),
  p({ id: "preset-protection-from-poison", name: "防护毒素", level: 2, school: "防护", range: "触及", duration: "1 小时", effect: "见规则书。" }),
  p({ id: "preset-ray-of-enfeeblement", name: "衰弱射线", level: 2, school: "死灵", duration: "专注，至多 1 分钟", concentration: true, saveAbility: "con", effect: "专注。体质豁免。" }),
  p({ id: "preset-rope-trick", name: "魔绳术", level: 2, school: "变化", range: "触及", duration: "1 小时", m: true, materials: "a segment of rope", effect: "见规则书。" }),
  p({ id: "preset-scorching-ray", name: "灼热射线", level: 2, school: "塑能", range: "120 尺", hasAttack: true, dmgCount: 2, dmgType: "火焰", effect: "远程法术攻击。2d6火焰。升环增强。" }),
  p({ id: "preset-see-invisibility", name: "识破隐形", level: 2, school: "预言", range: "自身", duration: "1 小时", m: true, materials: "a pinch of talc", effect: "见规则书。" }),
  p({ id: "preset-shatter", name: "粉碎音波", level: 2, school: "塑能", m: true, materials: "a chip of mica", saveAbility: "con", dmgCount: 3, dmgFaces: 8, dmgType: "雷鸣", effect: "体质豁免。3d8雷鸣。成功减半。升环增强。" }),
  p({ id: "preset-shining-smite", name: "闪耀斩", level: 2, school: "变化", castingTime: "1 个附赠动作", range: "自身", duration: "专注，至多 1 分钟", concentration: true, s: false, dmgCount: 2, dmgType: "光耀", effect: "专注。2d6光耀。升环增强。" }),
  p({ id: "preset-silence", name: "沉默术", level: 2, school: "幻术", range: "120 尺", duration: "专注，至多 10 分钟", concentration: true, ritual: true, effect: "仪式。专注。" }),
  p({ id: "preset-spider-climb", name: "蛛行术", level: 2, school: "变化", range: "触及", duration: "专注，至多 1 小时", concentration: true, m: true, materials: "a drop of bitumen and a spider", effect: "专注。升环增强。" }),
  p({ id: "preset-spike-growth", name: "荆棘丛生", level: 2, school: "变化", range: "150 尺", duration: "专注，至多 10 分钟", concentration: true, m: true, materials: "seven thorns", dmgCount: 2, dmgFaces: 4, dmgType: "穿刺", effect: "专注。2d4穿刺。" }),
  p({ id: "preset-spiritual-weapon", name: "灵体武器", level: 2, school: "塑能", castingTime: "1 个附赠动作", duration: "专注，至多 1 分钟", concentration: true, hasAttack: true, dmgCount: 1, dmgFaces: 8, dmgType: "力场", effect: "专注。近战法术攻击。1d8力场。升环增强。" }),
  p({ id: "preset-suggestion", name: "暗示术", level: 2, school: "惑控", range: "30 尺", duration: "专注，至多 8 小时", concentration: true, s: false, m: true, materials: "a drop of honey", saveAbility: "wis", effect: "专注。感知豁免。" }),
  p({ id: "preset-summon-beast", name: "野兽召唤术", level: 2, school: "咒法", range: "90 尺", duration: "专注，至多 1 小时", concentration: true, m: true, materials: "a feather, tuft of fur, and fish tail inside a gilded acorn worth 200+ GP", effect: "专注。升环增强。" }),
  p({ id: "preset-warding-bond", name: "守护之链", level: 2, school: "防护", range: "触及", duration: "1 小时", m: true, materials: "a pair of platinum rings worth 50+ GP each, which you and the target must wear for the duration", effect: "见规则书。" }),
  p({ id: "preset-web", name: "蛛网术", level: 2, school: "咒法", duration: "专注，至多 1 小时", concentration: true, m: true, materials: "a bit of spiderweb", saveAbility: "dex", dmgCount: 2, dmgFaces: 4, dmgType: "火焰", effect: "专注。敏捷豁免。2d4火焰。" }),
  p({ id: "preset-zone-of-truth", name: "诚实之域", level: 2, school: "惑控", duration: "10 分钟", saveAbility: "cha", effect: "魅力豁免。" }),
  p({ id: "preset-animate-dead", name: "活化死尸", level: 3, school: "死灵", castingTime: "1 分钟", range: "10 尺", m: true, materials: "a drop of blood, a piece of flesh, and a pinch of bone dust", effect: "升环增强。" }),
  p({ id: "preset-aura-of-vitality", name: "活力灵光", level: 3, school: "防护", range: "自身（30 尺光环）", duration: "专注，至多 1 分钟", concentration: true, s: false, dmgCount: 2, dmgType: "治疗", effect: "专注。恢复 2d6+调整值 生命。" }),
  p({ id: "preset-beacon-of-hope", name: "希望信标", level: 3, school: "防护", range: "30 尺", duration: "专注，至多 1 分钟", concentration: true, effect: "专注。" }),
  p({ id: "preset-bestow-curse", name: "降咒", level: 3, school: "死灵", range: "触及", duration: "专注，至多 1 分钟", concentration: true, saveAbility: "wis", dmgCount: 1, dmgFaces: 8, dmgType: "黯蚀", effect: "专注。感知豁免。1d8黯蚀。升环增强。" }),
  p({ id: "preset-blinding-smite", name: "致盲斩", level: 3, school: "塑能", castingTime: "1 个附赠动作", range: "自身", duration: "1 分钟", s: false, saveAbility: "con", dmgCount: 3, dmgFaces: 8, dmgType: "光耀", effect: "体质豁免。3d8光耀。升环增强。" }),
  p({ id: "preset-blink", name: "闪现术", level: 3, school: "变化", range: "自身", duration: "1 分钟", effect: "见规则书。" }),
  p({ id: "preset-call-lightning", name: "召雷术", level: 3, school: "咒法", range: "120 尺", duration: "专注，至多 10 分钟", concentration: true, saveAbility: "dex", dmgCount: 3, dmgFaces: 10, dmgType: "闪电", effect: "专注。敏捷豁免。3d10闪电。成功减半。升环增强。" }),
  p({ id: "preset-clairvoyance", name: "鹰眼术", level: 3, school: "预言", castingTime: "10 分钟", range: "1 里", duration: "专注，至多 10 分钟", concentration: true, m: true, materials: "a focus worth 100+ GP, either a jeweled horn for hearing or a glass eye for seeing", effect: "专注。" }),
  p({ id: "preset-conjure-animals", name: "咒唤兽群", level: 3, school: "咒法", duration: "专注，至多 10 分钟", concentration: true, saveAbility: "dex", dmgCount: 3, dmgFaces: 10, dmgType: "挥砍", effect: "专注。敏捷豁免。3d10挥砍。升环增强。" }),
  p({ id: "preset-conjure-barrage", name: "箭如雨下", level: 3, school: "咒法", range: "自身（60 尺锥状）", m: true, materials: "a Melee or Ranged weapon worth at least 1 CP", saveAbility: "dex", dmgCount: 5, dmgFaces: 8, dmgType: "力场", effect: "敏捷豁免。5d8力场。成功减半。升环增强。" }),
  p({ id: "preset-counterspell", name: "法术反制", level: 3, school: "防护", castingTime: "1 个反应", v: false, saveAbility: "con", effect: "体质豁免。" }),
  p({ id: "preset-create-food-and-water", name: "造粮术", level: 3, school: "咒法", range: "30 尺", effect: "见规则书。" }),
  p({ id: "preset-crusaders-mantle", name: "十字军披风", level: 3, school: "塑能", range: "自身（30 尺光环）", duration: "专注，至多 1 分钟", concentration: true, s: false, dmgCount: 1, dmgFaces: 4, dmgType: "光耀", effect: "专注。1d4光耀。" }),
  p({ id: "preset-daylight", name: "昼明术", level: 3, school: "塑能", duration: "1 小时", effect: "见规则书。" }),
  p({ id: "preset-dispel-magic", name: "解除魔法", level: 3, school: "防护", range: "120 尺", effect: "升环增强。" }),
  p({ id: "preset-elemental-weapon", name: "元素武器", level: 3, school: "变化", range: "触及", duration: "专注，至多 1 小时", concentration: true, dmgCount: 1, dmgFaces: 4, dmgType: "自选", effect: "专注。1d4自选。升环增强。" }),
  p({ id: "preset-fear", name: "恐惧术", level: 3, school: "幻术", range: "自身（30 尺锥状）", duration: "专注，至多 1 分钟", concentration: true, m: true, materials: "a white feather", saveAbility: "wis", effect: "专注。感知豁免。" }),
  p({ id: "preset-feign-death", name: "假死术", level: 3, school: "死灵", range: "触及", duration: "1 小时", ritual: true, m: true, materials: "a pinch of graveyard dirt", effect: "仪式。" }),
  p({ id: "preset-fireball", name: "火球术", level: 3, school: "塑能", range: "150 尺", m: true, materials: "a ball of bat guano and sulfur", saveAbility: "dex", dmgCount: 8, dmgType: "火焰", effect: "敏捷豁免。8d6火焰。成功减半。升环增强。" }),
  p({ id: "preset-fly", name: "飞行术", level: 3, school: "变化", range: "触及", duration: "专注，至多 10 分钟", concentration: true, m: true, materials: "a feather", effect: "专注。升环增强。" }),
  p({ id: "preset-gaseous-form", name: "气化形体", level: 3, school: "变化", range: "触及", duration: "专注，至多 1 小时", concentration: true, m: true, materials: "a bit of gauze", effect: "专注。升环增强。" }),
  p({ id: "preset-glyph-of-warding", name: "守卫刻文", level: 3, school: "防护", castingTime: "1 小时", range: "触及", duration: "直至解除", m: true, materials: "powdered diamond worth 200+ GP, which the spell consumes", saveAbility: "dex", dmgCount: 5, dmgFaces: 8, dmgType: "自选", effect: "敏捷豁免。5d8自选。成功减半。升环增强。" }),
  p({ id: "preset-haste", name: "加速术", level: 3, school: "变化", range: "30 尺", duration: "专注，至多 1 分钟", concentration: true, m: true, materials: "a shaving of licorice root", effect: "专注。" }),
  p({ id: "preset-hunger-of-hadar", name: "哈达之欲", level: 3, school: "咒法", range: "150 尺", duration: "专注，至多 1 分钟", concentration: true, m: true, materials: "a pickled tentacle", saveAbility: "dex", dmgCount: 2, dmgType: "自选", effect: "专注。敏捷豁免。2d6自选。升环增强。" }),
  p({ id: "preset-hypnotic-pattern", name: "催眠图纹", level: 3, school: "幻术", range: "120 尺", duration: "专注，至多 1 分钟", concentration: true, v: false, m: true, materials: "a pinch of confetti", saveAbility: "wis", effect: "专注。感知豁免。" }),
  p({ id: "preset-leomunds-tiny-hut", name: "李欧蒙小屋", level: 3, school: "塑能", castingTime: "1 分钟", range: "自身（10 尺光环）", duration: "8 小时", ritual: true, m: true, materials: "a crystal bead", effect: "仪式。" }),
  p({ id: "preset-lightning-arrow", name: "闪电箭矢", level: 3, school: "变化", castingTime: "1 个附赠动作", range: "自身", saveAbility: "dex", dmgCount: 4, dmgFaces: 8, dmgType: "闪电", effect: "敏捷豁免。4d8闪电。成功减半。升环增强。" }),
  p({ id: "preset-lightning-bolt", name: "闪电束", level: 3, school: "塑能", range: "自身（100 尺线状）", m: true, materials: "a bit of fur and a crystal rod", saveAbility: "dex", dmgCount: 8, dmgType: "闪电", effect: "敏捷豁免。8d6闪电。成功减半。升环增强。" }),
  p({ id: "preset-magic-circle", name: "防护法阵", level: 3, school: "防护", castingTime: "1 分钟", range: "10 尺", duration: "1 小时", m: true, materials: "salt and powdered silver worth 100+ GP, which the spell consumes", saveAbility: "cha", effect: "魅力豁免。升环增强。" }),
  p({ id: "preset-major-image", name: "高等幻影", level: 3, school: "幻术", range: "120 尺", duration: "专注，至多 10 分钟", concentration: true, m: true, materials: "a bit of fleece", effect: "专注。升环增强。" }),
  p({ id: "preset-mass-healing-word", name: "群体治愈真言", level: 3, school: "防护", castingTime: "1 个附赠动作", s: false, dmgCount: 2, dmgFaces: 4, dmgType: "治疗", effect: "恢复 2d4+调整值 生命。升环增强。" }),
  p({ id: "preset-meld-into-stone", name: "融身入石", level: 3, school: "变化", range: "触及", duration: "8 小时", ritual: true, dmgCount: 6, dmgType: "力场", effect: "仪式。6d6力场。" }),
  p({ id: "preset-nondetection", name: "回避侦测", level: 3, school: "防护", range: "触及", duration: "8 小时", m: true, materials: "a pinch of diamond dust worth 25+ GP, which the spell consumes", effect: "见规则书。" }),
  p({ id: "preset-phantom-steed", name: "魅影驹", level: 3, school: "幻术", castingTime: "1 分钟", range: "30 尺", duration: "1 小时", ritual: true, effect: "仪式。" }),
  p({ id: "preset-plant-growth", name: "植物滋长", level: 3, school: "变化", range: "150 尺", effect: "见规则书。" }),
  p({ id: "preset-protection-from-energy", name: "防护能量", level: 3, school: "防护", range: "触及", duration: "专注，至多 1 小时", concentration: true, effect: "专注。" }),
  p({ id: "preset-remove-curse", name: "移除诅咒", level: 3, school: "防护", range: "触及", effect: "见规则书。" }),
  p({ id: "preset-revivify", name: "回生术", level: 3, school: "死灵", range: "触及", m: true, materials: "a diamond worth 300+ GP, which the spell consumes", effect: "见规则书。" }),
  p({ id: "preset-sending", name: "短讯术", level: 3, school: "预言", range: "无限", m: true, materials: "a copper wire", effect: "见规则书。" }),
  p({ id: "preset-sleet-storm", name: "雪雨暴", level: 3, school: "咒法", range: "150 尺", duration: "专注，至多 1 分钟", concentration: true, m: true, materials: "a miniature umbrella", saveAbility: "dex", effect: "专注。敏捷豁免。" }),
  p({ id: "preset-slow", name: "缓慢术", level: 3, school: "变化", range: "120 尺", duration: "专注，至多 1 分钟", concentration: true, m: true, materials: "a drop of molasses", saveAbility: "wis", effect: "专注。感知豁免。" }),
  p({ id: "preset-speak-with-dead", name: "死者交谈", level: 3, school: "死灵", range: "10 尺", duration: "10 分钟", m: true, materials: "burning incense", effect: "见规则书。" }),
  p({ id: "preset-speak-with-plants", name: "植物交谈", level: 3, school: "变化", range: "自身（30 尺光环）", duration: "10 分钟", effect: "见规则书。" }),
  p({ id: "preset-spirit-guardians", name: "灵体卫士", level: 3, school: "咒法", range: "自身（15 尺光环）", duration: "专注，至多 10 分钟", concentration: true, m: true, materials: "a prayer scroll", saveAbility: "wis", dmgCount: 3, dmgFaces: 8, dmgType: "自选", effect: "专注。感知豁免。3d8自选。成功减半。升环增强。" }),
  p({ id: "preset-stinking-cloud", name: "臭云术", level: 3, school: "咒法", range: "90 尺", duration: "专注，至多 1 分钟", concentration: true, m: true, materials: "a rotten egg", saveAbility: "con", effect: "专注。体质豁免。" }),
  p({ id: "preset-summon-fey", name: "妖精召唤术", level: 3, school: "咒法", range: "90 尺", duration: "专注，至多 1 小时", concentration: true, m: true, materials: "a gilded flower worth 300+ GP", effect: "专注。升环增强。" }),
  p({ id: "preset-summon-undead", name: "亡灵召唤术", level: 3, school: "死灵", range: "90 尺", duration: "专注，至多 1 小时", concentration: true, m: true, materials: "a gilded skull worth 300+ GP", effect: "专注。升环增强。" }),
  p({ id: "preset-tongues", name: "巧言术", level: 3, school: "预言", range: "触及", duration: "1 小时", s: false, m: true, materials: "a miniature ziggurat", effect: "见规则书。" }),
  p({ id: "preset-vampiric-touch", name: "吸血鬼之触", level: 3, school: "死灵", range: "自身", duration: "专注，至多 1 分钟", concentration: true, hasAttack: true, dmgCount: 3, dmgType: "黯蚀", effect: "专注。近战法术攻击。3d6黯蚀。升环增强。" }),
  p({ id: "preset-water-breathing", name: "水下呼吸", level: 3, school: "变化", range: "30 尺", duration: "24 小时", ritual: true, m: true, materials: "a short reed", effect: "仪式。" }),
  p({ id: "preset-water-walk", name: "水上行走", level: 3, school: "变化", range: "30 尺", duration: "1 小时", ritual: true, m: true, materials: "a piece of cork", effect: "仪式。" }),
  p({ id: "preset-wind-wall", name: "风墙术", level: 3, school: "塑能", range: "120 尺", duration: "专注，至多 1 分钟", concentration: true, m: true, materials: "a fan and a feather", saveAbility: "str", dmgCount: 4, dmgFaces: 8, dmgType: "钝击", effect: "专注。力量豁免。4d8钝击。成功减半。" }),
  p({ id: "preset-arcane-eye", name: "秘法眼", level: 4, school: "预言", range: "30 尺", duration: "专注，至多 1 小时", concentration: true, m: true, materials: "a bit of bat fur", effect: "专注。" }),
  p({ id: "preset-aura-of-life", name: "生命灵光", level: 4, school: "防护", range: "自身（30 尺光环）", duration: "专注，至多 10 分钟", concentration: true, s: false, effect: "专注。" }),
  p({ id: "preset-aura-of-purity", name: "净化灵光", level: 4, school: "防护", range: "自身（30 尺光环）", duration: "专注，至多 10 分钟", concentration: true, s: false, effect: "专注。" }),
  p({ id: "preset-banishment", name: "放逐术", level: 4, school: "防护", range: "30 尺", duration: "专注，至多 1 分钟", concentration: true, m: true, materials: "a pentacle", saveAbility: "cha", effect: "专注。魅力豁免。升环增强。" }),
  p({ id: "preset-blight", name: "枯萎术", level: 4, school: "死灵", range: "30 尺", saveAbility: "con", dmgCount: 8, dmgFaces: 8, dmgType: "黯蚀", effect: "体质豁免。8d8黯蚀。成功减半。升环增强。" }),
  p({ id: "preset-charm-monster", name: "魅惑怪物", level: 4, school: "惑控", range: "30 尺", duration: "1 小时", saveAbility: "wis", effect: "感知豁免。升环增强。" }),
  p({ id: "preset-compulsion", name: "强迫术", level: 4, school: "惑控", range: "30 尺", duration: "专注，至多 1 分钟", concentration: true, saveAbility: "wis", effect: "专注。感知豁免。" }),
  p({ id: "preset-confusion", name: "困惑术", level: 4, school: "惑控", range: "90 尺", duration: "专注，至多 1 分钟", concentration: true, m: true, materials: "three nut shells", saveAbility: "wis", effect: "专注。感知豁免。升环增强。" }),
  p({ id: "preset-conjure-minor-elementals", name: "咒唤微元素群", level: 4, school: "咒法", range: "自身（15 尺光环）", duration: "专注，至多 10 分钟", concentration: true, dmgCount: 2, dmgFaces: 8, dmgType: "自选", effect: "专注。2d8自选。升环增强。" }),
  p({ id: "preset-conjure-woodland-beings", name: "咒唤林地卫士", level: 4, school: "咒法", range: "自身（10 尺光环）", duration: "专注，至多 10 分钟", concentration: true, saveAbility: "wis", dmgCount: 5, dmgFaces: 8, dmgType: "力场", effect: "专注。感知豁免。5d8力场。成功减半。升环增强。" }),
  p({ id: "preset-control-water", name: "操控水体", level: 4, school: "变化", range: "300 尺", duration: "专注，至多 10 分钟", concentration: true, m: true, materials: "a mixture of water and dust", saveAbility: "str", dmgCount: 2, dmgFaces: 8, dmgType: "钝击", effect: "专注。力量豁免。2d8钝击。成功减半。" }),
  p({ id: "preset-death-ward", name: "防死结界", level: 4, school: "防护", range: "触及", duration: "8 小时", effect: "见规则书。" }),
  p({ id: "preset-dimension-door", name: "任意门", level: 4, school: "咒法", range: "500 尺", s: false, dmgCount: 4, dmgType: "力场", effect: "4d6力场。" }),
  p({ id: "preset-divination", name: "预言术", level: 4, school: "预言", range: "自身", ritual: true, m: true, materials: "incense worth 25+ GP, which the spell consumes", effect: "仪式。" }),
  p({ id: "preset-dominate-beast", name: "支配野兽", level: 4, school: "惑控", duration: "专注，至多 1 分钟", concentration: true, saveAbility: "wis", effect: "专注。感知豁免。升环增强。" }),
  p({ id: "preset-evards-black-tentacles", name: "艾伐黑触手", level: 4, school: "咒法", range: "90 尺", duration: "专注，至多 1 分钟", concentration: true, m: true, materials: "a tentacle", saveAbility: "str", dmgCount: 3, dmgType: "钝击", effect: "专注。力量豁免。3d6钝击。" }),
  p({ id: "preset-fabricate", name: "鬼斧神工", level: 4, school: "变化", castingTime: "10 分钟", range: "120 尺", effect: "见规则书。" }),
  p({ id: "preset-fire-shield", name: "火焰护盾", level: 4, school: "塑能", range: "自身", duration: "10 分钟", m: true, materials: "a bit of phosphorus or a firefly", dmgCount: 2, dmgFaces: 8, dmgType: "自选", effect: "2d8自选。" }),
  p({ id: "preset-fount-of-moonlight", name: "月光涌泉", level: 4, school: "塑能", range: "自身", duration: "专注，至多 10 分钟", concentration: true, saveAbility: "con", dmgCount: 2, dmgType: "光耀", effect: "专注。体质豁免。2d6光耀。" }),
  p({ id: "preset-freedom-of-movement", name: "行动自如", level: 4, school: "防护", range: "触及", duration: "1 小时", m: true, materials: "a leather strap", effect: "升环增强。" }),
  p({ id: "preset-giant-insect", name: "巨虫术", level: 4, school: "咒法", duration: "专注，至多 10 分钟", concentration: true, effect: "专注。升环增强。" }),
  p({ id: "preset-grasping-vine", name: "擒抱藤", level: 4, school: "咒法", castingTime: "1 个附赠动作", duration: "专注，至多 1 分钟", concentration: true, hasAttack: true, dmgCount: 4, dmgFaces: 8, dmgType: "钝击", effect: "专注。近战法术攻击。4d8钝击。升环增强。" }),
  p({ id: "preset-greater-invisibility", name: "高等隐形术", level: 4, school: "幻术", range: "触及", duration: "专注，至多 1 分钟", concentration: true, effect: "专注。" }),
  p({ id: "preset-guardian-of-faith", name: "信仰守卫", level: 4, school: "咒法", range: "30 尺", duration: "8 小时", s: false, saveAbility: "dex", effect: "敏捷豁免。" }),
  p({ id: "preset-hallucinatory-terrain", name: "幻景", level: 4, school: "幻术", castingTime: "10 分钟", range: "300 尺", duration: "24 小时", m: true, materials: "a mushroom", effect: "见规则书。" }),
  p({ id: "preset-ice-storm", name: "冰风暴", level: 4, school: "塑能", range: "300 尺", m: true, materials: "a mitten", saveAbility: "dex", dmgCount: 2, dmgFaces: 10, dmgType: "自选", effect: "敏捷豁免。2d10自选。成功减半。升环增强。" }),
  p({ id: "preset-leomunds-secret-chest", name: "李欧蒙秘藏箱", level: 4, school: "咒法", range: "触及", duration: "直至解除", m: true, materials: "a chest, 3 feet by 2 feet by 2 feet, constructed from rare materials worth 5,000+ GP, and a Tiny replica of the chest made from the same materials worth 50+ GP", effect: "见规则书。" }),
  p({ id: "preset-locate-creature", name: "生物定位术", level: 4, school: "预言", range: "自身", duration: "专注，至多 1 小时", concentration: true, m: true, materials: "fur from a bloodhound", effect: "专注。" }),
  p({ id: "preset-mordenkainens-faithful-hound", name: "魔邓肯忠犬", level: 4, school: "咒法", range: "30 尺", duration: "8 小时", m: true, materials: "a silver whistle", saveAbility: "dex", dmgCount: 4, dmgFaces: 8, dmgType: "力场", effect: "敏捷豁免。4d8力场。" }),
  p({ id: "preset-mordenkainens-private-sanctum", name: "魔邓肯私人密室", level: 4, school: "防护", castingTime: "10 分钟", range: "120 尺", duration: "24 小时", m: true, materials: "a thin sheet of lead", effect: "升环增强。" }),
  p({ id: "preset-otilukes-resilient-sphere", name: "欧提路克魔封法球", level: 4, school: "防护", range: "30 尺", duration: "专注，至多 1 分钟", concentration: true, m: true, materials: "a glass sphere", saveAbility: "dex", effect: "专注。敏捷豁免。" }),
  p({ id: "preset-phantasmal-killer", name: "魅影杀手", level: 4, school: "幻术", range: "120 尺", duration: "专注，至多 1 分钟", concentration: true, saveAbility: "wis", dmgCount: 4, dmgFaces: 10, dmgType: "心灵", effect: "专注。感知豁免。4d10心灵。成功减半。升环增强。" }),
  p({ id: "preset-polymorph", name: "变形术", level: 4, school: "变化", duration: "专注，至多 1 小时", concentration: true, m: true, materials: "a caterpillar cocoon", saveAbility: "wis", effect: "专注。感知豁免。" }),
  p({ id: "preset-staggering-smite", name: "惊惧斩", level: 4, school: "惑控", castingTime: "1 个附赠动作", range: "自身", s: false, saveAbility: "wis", dmgCount: 4, dmgType: "心灵", effect: "感知豁免。4d6心灵。升环增强。" }),
  p({ id: "preset-stone-shape", name: "塑石术", level: 4, school: "变化", range: "触及", m: true, materials: "soft clay", effect: "见规则书。" }),
  p({ id: "preset-stoneskin", name: "石肤术", level: 4, school: "变化", range: "触及", duration: "专注，至多 1 小时", concentration: true, m: true, materials: "diamond dust worth 100+ GP, which the spell consumes", effect: "专注。" }),
  p({ id: "preset-summon-aberration", name: "异怪召唤术", level: 4, school: "咒法", range: "90 尺", duration: "专注，至多 1 小时", concentration: true, m: true, materials: "a pickled tentacle and an eyeball in a platinum-inlaid vial worth 400+ GP", effect: "专注。升环增强。" }),
  p({ id: "preset-summon-construct", name: "构装召唤术", level: 4, school: "咒法", range: "90 尺", duration: "专注，至多 1 小时", concentration: true, m: true, materials: "a lockbox worth 400+ GP", effect: "专注。升环增强。" }),
  p({ id: "preset-summon-elemental", name: "元素召唤术", level: 4, school: "咒法", range: "90 尺", duration: "专注，至多 1 小时", concentration: true, m: true, materials: "air, a pebble, ash, and water inside a gold-inlaid vial worth 400+ GP", effect: "专注。升环增强。" }),
  p({ id: "preset-vitriolic-sphere", name: "硫酸法球", level: 4, school: "塑能", range: "150 尺", m: true, materials: "a drop of bile", saveAbility: "dex", dmgCount: 10, dmgFaces: 4, dmgType: "强酸", effect: "敏捷豁免。10d4强酸。升环增强。" }),
  p({ id: "preset-wall-of-fire", name: "火墙术", level: 4, school: "塑能", range: "120 尺", duration: "专注，至多 1 分钟", concentration: true, m: true, materials: "a piece of charcoal", saveAbility: "dex", dmgCount: 5, dmgFaces: 8, dmgType: "火焰", effect: "专注。敏捷豁免。5d8火焰。成功减半。升环增强。" }),
  p({ id: "preset-animate-objects", name: "活化物件", level: 5, school: "变化", range: "120 尺", duration: "专注，至多 1 分钟", concentration: true, effect: "专注。升环增强。" }),
  p({ id: "preset-antilife-shell", name: "防活物护罩", level: 5, school: "防护", range: "自身（10 尺光环）", duration: "专注，至多 1 小时", concentration: true, effect: "专注。" }),
  p({ id: "preset-awaken", name: "启蒙术", level: 5, school: "变化", castingTime: "8 小时", range: "触及", m: true, materials: "an agate worth 1,000+ GP, which the spell consumes", effect: "见规则书。" }),
  p({ id: "preset-banishing-smite", name: "放逐斩", level: 5, school: "咒法", castingTime: "1 个附赠动作", range: "自身", duration: "专注，至多 1 分钟", concentration: true, s: false, dmgCount: 5, dmgFaces: 10, dmgType: "力场", effect: "专注。5d10力场。" }),
  p({ id: "preset-bigbys-hand", name: "毕格比之手", level: 5, school: "塑能", range: "120 尺", duration: "专注，至多 1 分钟", concentration: true, m: true, materials: "an eggshell and a glove", hasAttack: true, saveAbility: "dex", dmgCount: 5, dmgFaces: 8, dmgType: "自选", effect: "专注。近战法术攻击。敏捷豁免。5d8自选。升环增强。" }),
  p({ id: "preset-circle-of-power", name: "原力法阵", level: 5, school: "防护", range: "自身（30 尺光环）", duration: "专注，至多 10 分钟", concentration: true, s: false, effect: "专注。" }),
  p({ id: "preset-cloudkill", name: "死云术", level: 5, school: "咒法", range: "120 尺", duration: "专注，至多 10 分钟", concentration: true, saveAbility: "con", dmgCount: 5, dmgFaces: 8, dmgType: "毒素", effect: "专注。体质豁免。5d8毒素。成功减半。升环增强。" }),
  p({ id: "preset-commune", name: "通神术", level: 5, school: "预言", castingTime: "1 分钟", range: "自身", duration: "1 分钟", ritual: true, m: true, materials: "incense", effect: "仪式。" }),
  p({ id: "preset-commune-with-nature", name: "问道自然", level: 5, school: "预言", castingTime: "1 分钟", range: "自身", duration: "1 分钟", ritual: true, effect: "仪式。" }),
  p({ id: "preset-cone-of-cold", name: "寒冰锥", level: 5, school: "塑能", range: "自身（60 尺锥状）", m: true, materials: "a small crystal or glass cone", saveAbility: "con", dmgCount: 8, dmgFaces: 8, dmgType: "冷冻", effect: "体质豁免。8d8冷冻。成功减半。升环增强。" }),
  p({ id: "preset-conjure-elemental", name: "咒唤元素", level: 5, school: "咒法", duration: "专注，至多 10 分钟", concentration: true, saveAbility: "dex", dmgCount: 8, dmgFaces: 8, dmgType: "自选", effect: "专注。敏捷豁免。8d8自选。升环增强。" }),
  p({ id: "preset-conjure-volley", name: "万箭齐发", level: 5, school: "咒法", range: "150 尺", m: true, materials: "a Melee or Ranged weapon worth at least 1 CP", saveAbility: "dex", dmgCount: 8, dmgFaces: 8, dmgType: "力场", effect: "敏捷豁免。8d8力场。成功减半。" }),
  p({ id: "preset-contact-other-plane", name: "异界探知", level: 5, school: "预言", castingTime: "1 分钟", range: "自身", duration: "1 分钟", ritual: true, s: false, saveAbility: "int", dmgCount: 6, dmgType: "心灵", effect: "仪式。智力豁免。6d6心灵。" }),
  p({ id: "preset-contagion", name: "疫病术", level: 5, school: "死灵", range: "触及", duration: "7 日", saveAbility: "con", dmgCount: 11, dmgFaces: 8, dmgType: "黯蚀", effect: "体质豁免。11d8黯蚀。" }),
  p({ id: "preset-creation", name: "造物术", level: 5, school: "幻术", castingTime: "1 分钟", range: "30 尺", duration: "特殊", m: true, materials: "a paintbrush", effect: "升环增强。" }),
  p({ id: "preset-destructive-wave", name: "湮灭波", level: 5, school: "塑能", range: "自身（30 尺光环）", s: false, saveAbility: "con", dmgCount: 5, dmgType: "自选", effect: "体质豁免。5d6自选。成功减半。" }),
  p({ id: "preset-dispel-evil-and-good", name: "驱逐善恶", level: 5, school: "防护", range: "自身", duration: "专注，至多 1 分钟", concentration: true, m: true, materials: "powdered silver and iron", saveAbility: "cha", effect: "专注。魅力豁免。" }),
  p({ id: "preset-dominate-person", name: "支配类人", level: 5, school: "惑控", duration: "专注，至多 1 分钟", concentration: true, saveAbility: "wis", effect: "专注。感知豁免。升环增强。" }),
  p({ id: "preset-dream", name: "托梦术", level: 5, school: "幻术", castingTime: "1 分钟", range: "自身", duration: "8 小时", m: true, materials: "a handful of sand", saveAbility: "wis", dmgCount: 3, dmgType: "心灵", effect: "感知豁免。3d6心灵。" }),
  p({ id: "preset-flame-strike", name: "焰击术", level: 5, school: "塑能", m: true, materials: "a pinch of sulfur", saveAbility: "dex", dmgCount: 5, dmgType: "自选", effect: "敏捷豁免。5d6自选。成功减半。升环增强。" }),
  p({ id: "preset-geas", name: "指使术", level: 5, school: "惑控", castingTime: "1 分钟", duration: "30 日", s: false, saveAbility: "wis", dmgCount: 5, dmgFaces: 10, dmgType: "心灵", effect: "感知豁免。5d10心灵。升环增强。" }),
  p({ id: "preset-greater-restoration", name: "高等复原术", level: 5, school: "防护", range: "触及", m: true, materials: "diamond dust worth 100+ GP, which the spell consumes", effect: "见规则书。" }),
  p({ id: "preset-hallow", name: "圣居", level: 5, school: "防护", castingTime: "24 小时", range: "触及", duration: "直至解除", m: true, materials: "incense worth 1,000+ GP, which the spell consumes", effect: "见规则书。" }),
  p({ id: "preset-hold-monster", name: "定身怪物", level: 5, school: "惑控", range: "90 尺", duration: "专注，至多 1 分钟", concentration: true, m: true, materials: "a straight piece of iron", saveAbility: "wis", effect: "专注。感知豁免。升环增强。" }),
  p({ id: "preset-insect-plague", name: "疫病虫群", level: 5, school: "咒法", range: "300 尺", duration: "专注，至多 10 分钟", concentration: true, m: true, materials: "a locust", saveAbility: "con", dmgCount: 4, dmgFaces: 10, dmgType: "穿刺", effect: "专注。体质豁免。4d10穿刺。成功减半。升环增强。" }),
  p({ id: "preset-jallarzis-storm-of-radiance", name: "贾拉兹光耀风暴", level: 5, school: "塑能", range: "120 尺", duration: "专注，至多 1 分钟", concentration: true, m: true, materials: "a pinch of phosphorus", saveAbility: "con", dmgCount: 2, dmgFaces: 10, dmgType: "自选", effect: "专注。体质豁免。2d10自选。成功减半。升环增强。" }),
  p({ id: "preset-legend-lore", name: "通晓传奇", level: 5, school: "预言", castingTime: "10 分钟", range: "自身", m: true, materials: "incense worth 250+ GP, which the spell consumes, and four ivory strips worth 50+ GP each", effect: "见规则书。" }),
  p({ id: "preset-mass-cure-wounds", name: "群体疗伤术", level: 5, school: "防护", dmgCount: 5, dmgFaces: 8, dmgType: "治疗", effect: "恢复 5d8+调整值 生命。升环增强。" }),
  p({ id: "preset-mislead", name: "假象术", level: 5, school: "幻术", range: "自身", duration: "专注，至多 1 小时", concentration: true, v: false, effect: "专注。" }),
  p({ id: "preset-modify-memory", name: "篡改记忆", level: 5, school: "惑控", range: "30 尺", duration: "专注，至多 1 分钟", concentration: true, saveAbility: "wis", effect: "专注。感知豁免。升环增强。" }),
  p({ id: "preset-passwall", name: "穿墙术", level: 5, school: "变化", range: "30 尺", duration: "1 小时", m: true, materials: "a pinch of sesame seeds", effect: "见规则书。" }),
  p({ id: "preset-planar-binding", name: "异界誓缚", level: 5, school: "防护", castingTime: "1 小时", duration: "24 小时", m: true, materials: "a jewel worth 1,000+ GP, which the spell consumes", saveAbility: "cha", effect: "魅力豁免。升环增强。" }),
  p({ id: "preset-raise-dead", name: "死者复活", level: 5, school: "死灵", castingTime: "1 小时", range: "触及", m: true, materials: "a diamond worth 500+ GP, which the spell consumes", effect: "见规则书。" }),
  p({ id: "preset-rarys-telepathic-bond", name: "拉瑞心灵联结", level: 5, school: "预言", range: "30 尺", duration: "1 小时", ritual: true, m: true, materials: "two eggs", effect: "仪式。" }),
  p({ id: "preset-reincarnate", name: "转生术", level: 5, school: "死灵", castingTime: "1 小时", range: "触及", m: true, materials: "rare oils worth 1,000+ GP, which the spell consumes", effect: "见规则书。" }),
  p({ id: "preset-scrying", name: "探知术", level: 5, school: "预言", castingTime: "10 分钟", range: "自身", duration: "专注，至多 10 分钟", concentration: true, m: true, materials: "a focus worth 1,000+ GP, such as a crystal ball, mirror, or water-filled font", saveAbility: "wis", effect: "专注。感知豁免。" }),
  p({ id: "preset-seeming", name: "伪装术", level: 5, school: "幻术", range: "30 尺", duration: "8 小时", saveAbility: "cha", effect: "魅力豁免。" }),
  p({ id: "preset-steel-wind-strike", name: "钢风斩", level: 5, school: "咒法", range: "30 尺", v: false, m: true, materials: "a Melee weapon worth 1+ SP", hasAttack: true, dmgCount: 6, dmgFaces: 10, dmgType: "力场", effect: "近战法术攻击。6d10力场。" }),
  p({ id: "preset-summon-celestial", name: "天界召唤术", level: 5, school: "咒法", range: "90 尺", duration: "专注，至多 1 小时", concentration: true, m: true, materials: "a reliquary worth 500+ GP", effect: "专注。升环增强。" }),
  p({ id: "preset-summon-dragon", name: "龙类召唤术", level: 5, school: "咒法", duration: "专注，至多 1 小时", concentration: true, m: true, materials: "an object with the image of a dragon engraved on it worth 500+ GP", effect: "专注。升环增强。" }),
  p({ id: "preset-swift-quiver", name: "迅捷箭袋", level: 5, school: "变化", castingTime: "1 个附赠动作", range: "自身", duration: "专注，至多 1 分钟", concentration: true, m: true, materials: "a Quiver worth 1+ GP", effect: "专注。" }),
  p({ id: "preset-synaptic-static", name: "突触静止", level: 5, school: "惑控", range: "120 尺", saveAbility: "int", dmgCount: 8, dmgType: "心灵", effect: "智力豁免。8d6心灵。成功减半。" }),
  p({ id: "preset-telekinesis", name: "心灵遥控", level: 5, school: "变化", duration: "专注，至多 10 分钟", concentration: true, saveAbility: "str", effect: "专注。力量豁免。" }),
  p({ id: "preset-teleportation-circle", name: "传送法阵", level: 5, school: "咒法", castingTime: "1 分钟", range: "10 尺", duration: "1 轮", s: false, m: true, materials: "rare inks worth 50+ GP, which the spell consumes", effect: "见规则书。" }),
  p({ id: "preset-tree-stride", name: "树跃术", level: 5, school: "咒法", range: "自身", duration: "专注，至多 1 分钟", concentration: true, effect: "专注。" }),
  p({ id: "preset-wall-of-force", name: "力场墙", level: 5, school: "塑能", range: "120 尺", duration: "专注，至多 10 分钟", concentration: true, m: true, materials: "a shard of glass", effect: "专注。" }),
  p({ id: "preset-wall-of-stone", name: "石墙术", level: 5, school: "塑能", range: "120 尺", duration: "专注，至多 10 分钟", concentration: true, m: true, materials: "a cube of granite", saveAbility: "dex", effect: "专注。敏捷豁免。" }),
  p({ id: "preset-yolandes-regal-presence", name: "悠兰德王者威仪", level: 5, school: "惑控", range: "自身（10 尺光环）", duration: "专注，至多 1 分钟", concentration: true, m: true, materials: "a miniature tiara", saveAbility: "wis", dmgCount: 4, dmgType: "心灵", effect: "专注。感知豁免。4d6心灵。成功减半。" }),
  p({ id: "preset-arcane-gate", name: "秘法门", level: 6, school: "咒法", range: "500 尺", duration: "专注，至多 10 分钟", concentration: true, effect: "专注。" }),
  p({ id: "preset-blade-barrier", name: "剑刃护壁", level: 6, school: "塑能", range: "90 尺", duration: "专注，至多 10 分钟", concentration: true, saveAbility: "dex", dmgCount: 6, dmgFaces: 10, dmgType: "力场", effect: "专注。敏捷豁免。6d10力场。成功减半。" }),
  p({ id: "preset-chain-lightning", name: "连锁闪电", level: 6, school: "塑能", range: "150 尺", m: true, materials: "three silver pins", saveAbility: "dex", dmgCount: 10, dmgFaces: 8, dmgType: "闪电", effect: "敏捷豁免。10d8闪电。成功减半。升环增强。" }),
  p({ id: "preset-circle-of-death", name: "死亡法阵", level: 6, school: "死灵", range: "150 尺", m: true, materials: "the powder of a crushed black pearl worth 500+ GP", saveAbility: "con", dmgCount: 8, dmgFaces: 8, dmgType: "黯蚀", effect: "体质豁免。8d8黯蚀。成功减半。升环增强。" }),
  p({ id: "preset-conjure-fey", name: "咒唤妖精", level: 6, school: "咒法", duration: "专注，至多 10 分钟", concentration: true, dmgCount: 3, dmgFaces: 12, dmgType: "心灵", effect: "专注。3d12心灵。升环增强。" }),
  p({ id: "preset-contingency", name: "触发术", level: 6, school: "防护", castingTime: "10 分钟", range: "自身", duration: "10 日", m: true, materials: "a gem-encrusted statuette of yourself worth 1,500+ GP", effect: "见规则书。" }),
  p({ id: "preset-create-undead", name: "唤起死灵", level: 6, school: "死灵", castingTime: "1 分钟", range: "10 尺", m: true, materials: "one 150+ GP black onyx stone for each corpse", effect: "升环增强。" }),
  p({ id: "preset-disintegrate", name: "解离术", level: 6, school: "变化", m: true, materials: "a lodestone and dust", saveAbility: "dex", dmgCount: 10, dmgBonus: 40, dmgType: "力场", effect: "敏捷豁免。10d6+40力场。升环增强。" }),
  p({ id: "preset-drawmijs-instant-summons", name: "卓姆吉瞬间召唤", level: 6, school: "咒法", castingTime: "1 分钟", range: "触及", duration: "直至解除", ritual: true, m: true, materials: "a sapphire worth 1,000+ GP", effect: "仪式。" }),
  p({ id: "preset-eyebite", name: "摄心目光", level: 6, school: "死灵", range: "自身", duration: "专注，至多 1 分钟", concentration: true, saveAbility: "wis", effect: "专注。感知豁免。" }),
  p({ id: "preset-find-the-path", name: "寻路术", level: 6, school: "预言", castingTime: "1 分钟", range: "自身", duration: "专注，至多 1 日", concentration: true, m: true, materials: "a set of divination tools—such as cards or runes—worth 100+ GP", effect: "专注。" }),
  p({ id: "preset-flesh-to-stone", name: "石化术", level: 6, school: "变化", duration: "专注，至多 1 分钟", concentration: true, m: true, materials: "a cockatrice feather", saveAbility: "con", effect: "专注。体质豁免。" }),
  p({ id: "preset-forbiddance", name: "禁制术", level: 6, school: "防护", castingTime: "10 分钟", range: "触及", duration: "1 日", ritual: true, m: true, materials: "ruby dust worth 1,000+ GP", dmgCount: 5, dmgFaces: 10, dmgType: "自选", effect: "仪式。5d10自选。" }),
  p({ id: "preset-globe-of-invulnerability", name: "法术无效结界", level: 6, school: "防护", range: "自身（10 尺光环）", duration: "专注，至多 1 分钟", concentration: true, m: true, materials: "a glass bead", effect: "专注。升环增强。" }),
  p({ id: "preset-guards-and-wards", name: "铜墙铁壁", level: 6, school: "防护", castingTime: "1 小时", range: "触及", duration: "24 小时", m: true, materials: "a silver rod worth 10+ GP", effect: "见规则书。" }),
  p({ id: "preset-harm", name: "重伤术", level: 6, school: "死灵", saveAbility: "con", dmgCount: 14, dmgType: "黯蚀", effect: "体质豁免。14d6黯蚀。成功减半。" }),
  p({ id: "preset-heal", name: "医疗术", level: 6, school: "防护", effect: "升环增强。" }),
  p({ id: "preset-heroes-feast", name: "英雄宴", level: 6, school: "咒法", castingTime: "10 分钟", range: "自身（10 尺立方）", m: true, materials: "a gem-encrusted bowl worth 1,000+ GP, which the spell consumes", dmgCount: 2, dmgFaces: 10, dmgType: "治疗", effect: "恢复 2d10+调整值 生命。" }),
  p({ id: "preset-magic-jar", name: "魔魂壶", level: 6, school: "死灵", castingTime: "1 分钟", range: "自身", duration: "直至解除", m: true, materials: "a gem, crystal, or reliquary worth 500+ GP", saveAbility: "cha", effect: "魅力豁免。" }),
  p({ id: "preset-mass-suggestion", name: "群体暗示术", level: 6, school: "惑控", duration: "24 小时", s: false, m: true, materials: "a snake's tongue", saveAbility: "wis", effect: "感知豁免。升环增强。" }),
  p({ id: "preset-move-earth", name: "地动术", level: 6, school: "变化", range: "120 尺", duration: "专注，至多 2 小时", concentration: true, m: true, materials: "a miniature shovel", effect: "专注。" }),
  p({ id: "preset-otilukes-freezing-sphere", name: "欧提路克冰冻法球", level: 6, school: "塑能", range: "300 尺", m: true, materials: "a miniature crystal sphere", saveAbility: "con", dmgCount: 10, dmgType: "冷冻", effect: "体质豁免。10d6冷冻。成功减半。升环增强。" }),
  p({ id: "preset-ottos-irresistible-dance", name: "奥图狂舞术", level: 6, school: "惑控", range: "30 尺", duration: "专注，至多 1 分钟", concentration: true, s: false, saveAbility: "wis", effect: "专注。感知豁免。" }),
  p({ id: "preset-planar-ally", name: "异界誓盟", level: 6, school: "咒法", castingTime: "10 分钟", effect: "见规则书。" }),
  p({ id: "preset-programmed-illusion", name: "预置幻影", level: 6, school: "幻术", range: "120 尺", duration: "直至解除", m: true, materials: "jade dust worth 25+ GP", effect: "见规则书。" }),
  p({ id: "preset-summon-fiend", name: "邪魔召唤术", level: 6, school: "咒法", range: "90 尺", duration: "专注，至多 1 小时", concentration: true, m: true, materials: "a bloody vial worth 600+ GP", effect: "专注。升环增强。" }),
  p({ id: "preset-sunbeam", name: "阳炎射线", level: 6, school: "塑能", range: "自身（60 尺线状）", duration: "专注，至多 1 分钟", concentration: true, m: true, materials: "a magnifying glass", saveAbility: "con", dmgCount: 6, dmgFaces: 8, dmgType: "光耀", effect: "专注。体质豁免。6d8光耀。成功减半。" }),
  p({ id: "preset-tashas-bubbling-cauldron", name: "塔莎泡泡坩埚", level: 6, school: "咒法", range: "5 尺", duration: "10 分钟", m: true, materials: "a gilded ladle worth 500 + GP", effect: "见规则书。" }),
  p({ id: "preset-transport-via-plants", name: "木遁术", level: 6, school: "咒法", range: "10 尺", duration: "10 分钟", effect: "见规则书。" }),
  p({ id: "preset-true-seeing", name: "真知术", level: 6, school: "预言", range: "触及", duration: "1 小时", m: true, materials: "mushroom powder worth 25+ GP, which the spell consumes", effect: "见规则书。" }),
  p({ id: "preset-wall-of-ice", name: "冰墙术", level: 6, school: "塑能", range: "120 尺", duration: "专注，至多 10 分钟", concentration: true, m: true, materials: "a piece of quartz", saveAbility: "dex", dmgCount: 10, dmgType: "冷冻", effect: "专注。敏捷豁免。10d6冷冻。成功减半。升环增强。" }),
  p({ id: "preset-wall-of-thorns", name: "棘墙术", level: 6, school: "咒法", range: "120 尺", duration: "专注，至多 10 分钟", concentration: true, m: true, materials: "a handful of thorns", saveAbility: "dex", dmgCount: 7, dmgFaces: 8, dmgType: "自选", effect: "专注。敏捷豁免。7d8自选。成功减半。升环增强。" }),
  p({ id: "preset-wind-walk", name: "御风而行", level: 6, school: "变化", castingTime: "1 分钟", range: "30 尺", duration: "8 小时", m: true, materials: "a candle", effect: "见规则书。" }),
  p({ id: "preset-word-of-recall", name: "回返真言", level: 6, school: "咒法", range: "5 尺", s: false, effect: "见规则书。" }),
  p({ id: "preset-conjure-celestial", name: "咒唤圣光", level: 7, school: "咒法", range: "90 尺", duration: "专注，至多 10 分钟", concentration: true, saveAbility: "dex", dmgCount: 6, dmgFaces: 12, dmgType: "光耀", effect: "专注。敏捷豁免。6d12光耀。成功减半。升环增强。" }),
  p({ id: "preset-delayed-blast-fireball", name: "延迟爆裂火球", level: 7, school: "塑能", range: "150 尺", duration: "专注，至多 1 分钟", concentration: true, m: true, materials: "a ball of bat guano and sulfur", saveAbility: "dex", dmgCount: 12, dmgType: "火焰", effect: "专注。敏捷豁免。12d6火焰。成功减半。升环增强。" }),
  p({ id: "preset-divine-word", name: "圣言术", level: 7, school: "塑能", castingTime: "1 个附赠动作", range: "30 尺", s: false, saveAbility: "cha", effect: "魅力豁免。" }),
  p({ id: "preset-etherealness", name: "以太化", level: 7, school: "咒法", range: "自身", duration: "8 小时", effect: "升环增强。" }),
  p({ id: "preset-finger-of-death", name: "死亡一指", level: 7, school: "死灵", saveAbility: "con", dmgCount: 7, dmgFaces: 8, dmgBonus: 30, dmgType: "黯蚀", effect: "体质豁免。7d8+30黯蚀。成功减半。" }),
  p({ id: "preset-fire-storm", name: "火焰风暴", level: 7, school: "塑能", range: "150 尺", saveAbility: "dex", dmgCount: 7, dmgFaces: 10, dmgType: "火焰", effect: "敏捷豁免。7d10火焰。成功减半。" }),
  p({ id: "preset-forcecage", name: "力场监牢", level: 7, school: "塑能", range: "100 尺", duration: "专注，至多 1 小时", concentration: true, m: true, materials: "ruby dust worth 1,500+ GP, which the spell consumes", saveAbility: "cha", effect: "专注。魅力豁免。" }),
  p({ id: "preset-mirage-arcane", name: "海市蜃楼", level: 7, school: "幻术", castingTime: "10 分钟", range: "视线", duration: "10 日", effect: "见规则书。" }),
  p({ id: "preset-mordenkainens-magnificent-mansion", name: "魔邓肯豪宅术", level: 7, school: "咒法", castingTime: "1 分钟", range: "300 尺", duration: "24 小时", m: true, materials: "a miniature door worth 15+ GP", effect: "见规则书。" }),
  p({ id: "preset-mordenkainens-sword", name: "魔邓肯之剑", level: 7, school: "塑能", range: "90 尺", duration: "专注，至多 1 分钟", concentration: true, m: true, materials: "a miniature sword worth 250+ GP", hasAttack: true, dmgCount: 4, dmgFaces: 12, dmgType: "力场", effect: "专注。近战法术攻击。4d12力场。" }),
  p({ id: "preset-plane-shift", name: "位面转移", level: 7, school: "咒法", range: "触及", m: true, materials: "a forked, metal rod worth 250+ GP and attuned to a plane of existence", effect: "见规则书。" }),
  p({ id: "preset-power-word-fortify", name: "律令巩固", level: 7, school: "惑控", s: false, effect: "见规则书。" }),
  p({ id: "preset-prismatic-spray", name: "虹光喷射", level: 7, school: "塑能", range: "自身（60 尺锥状）", saveAbility: "dex", dmgCount: 12, dmgType: "自选", effect: "敏捷豁免。12d6自选。成功减半。" }),
  p({ id: "preset-project-image", name: "投影术", level: 7, school: "幻术", range: "500 里", duration: "专注，至多 1 日", concentration: true, m: true, materials: "a statuette of yourself worth 5+ GP", effect: "专注。" }),
  p({ id: "preset-regenerate", name: "再生术", level: 7, school: "变化", castingTime: "1 分钟", range: "触及", duration: "1 小时", m: true, materials: "a prayer wheel", dmgCount: 4, dmgFaces: 8, dmgBonus: 15, dmgType: "治疗", effect: "恢复 4d8+15+调整值 生命。" }),
  p({ id: "preset-resurrection", name: "复生术", level: 7, school: "死灵", castingTime: "1 小时", range: "触及", m: true, materials: "a diamond worth 1,000+ GP, which the spell consumes", effect: "见规则书。" }),
  p({ id: "preset-reverse-gravity", name: "反转重力", level: 7, school: "变化", range: "100 尺", duration: "专注，至多 1 分钟", concentration: true, m: true, materials: "a lodestone and iron filings", saveAbility: "dex", effect: "专注。敏捷豁免。" }),
  p({ id: "preset-sequester", name: "隔离术", level: 7, school: "变化", range: "触及", duration: "直至解除", m: true, materials: "gem dust worth 5,000+ GP, which the spell consumes", effect: "见规则书。" }),
  p({ id: "preset-simulacrum", name: "拟像术", level: 7, school: "幻术", castingTime: "12 小时", range: "触及", duration: "直至解除", m: true, materials: "powdered ruby worth 1,500+ GP, which the spell consumes", effect: "见规则书。" }),
  p({ id: "preset-symbol", name: "徽记术", level: 7, school: "防护", castingTime: "1 分钟", range: "触及", duration: "直至解除", m: true, materials: "powdered diamond worth 1,000+ GP, which the spell consumes", saveAbility: "con", dmgCount: 10, dmgFaces: 10, dmgType: "黯蚀", effect: "体质豁免。10d10黯蚀。成功减半。" }),
  p({ id: "preset-teleport", name: "传送术", level: 7, school: "咒法", range: "10 尺", s: false, dmgCount: 3, dmgFaces: 10, dmgType: "力场", effect: "3d10力场。" }),
  p({ id: "preset-animal-shapes", name: "动物形态", level: 8, school: "变化", range: "30 尺", duration: "24 小时", effect: "见规则书。" }),
  p({ id: "preset-antimagic-field", name: "反魔法场", level: 8, school: "防护", range: "自身（10 尺光环）", duration: "专注，至多 1 小时", concentration: true, m: true, materials: "iron filings", effect: "专注。" }),
  p({ id: "preset-antipathy-sympathy", name: "嫌恶术/关怀术", level: 8, school: "惑控", castingTime: "1 小时", duration: "10 日", m: true, materials: "a mix of vinegar and honey", saveAbility: "wis", effect: "感知豁免。" }),
  p({ id: "preset-befuddlement", name: "摧心术", level: 8, school: "惑控", range: "150 尺", m: true, materials: "a key ring with no keys", saveAbility: "int", dmgCount: 10, dmgFaces: 12, dmgType: "心灵", effect: "智力豁免。10d12心灵。成功减半。" }),
  p({ id: "preset-clone", name: "克隆术", level: 8, school: "死灵", castingTime: "1 小时", range: "触及", m: true, materials: "a diamond worth 1,000+ GP, which the spell consumes, and a sealable vessel worth 2,000+ GP that is large enough to hold the creature being cloned", effect: "见规则书。" }),
  p({ id: "preset-control-weather", name: "操控天气", level: 8, school: "变化", castingTime: "10 分钟", range: "自身（5 里球状）", duration: "专注，至多 8 小时", concentration: true, m: true, materials: "burning incense", effect: "专注。" }),
  p({ id: "preset-demiplane", name: "半位面", level: 8, school: "咒法", duration: "1 小时", v: false, effect: "见规则书。" }),
  p({ id: "preset-dominate-monster", name: "支配怪物", level: 8, school: "惑控", duration: "专注，至多 1 小时", concentration: true, saveAbility: "wis", effect: "专注。感知豁免。升环增强。" }),
  p({ id: "preset-earthquake", name: "地震术", level: 8, school: "变化", range: "500 尺", duration: "专注，至多 1 分钟", concentration: true, m: true, materials: "a fractured rock", saveAbility: "con", dmgCount: 12, dmgType: "钝击", effect: "专注。体质豁免。12d6钝击。成功减半。" }),
  p({ id: "preset-glibness", name: "花言巧语", level: 8, school: "惑控", range: "自身", duration: "1 小时", s: false, effect: "见规则书。" }),
  p({ id: "preset-holy-aura", name: "圣洁灵光", level: 8, school: "防护", range: "自身（30 尺光环）", duration: "专注，至多 1 分钟", concentration: true, m: true, materials: "a reliquary worth 1,000+ GP", saveAbility: "con", effect: "专注。体质豁免。" }),
  p({ id: "preset-incendiary-cloud", name: "焚云术", level: 8, school: "咒法", range: "150 尺", duration: "专注，至多 1 分钟", concentration: true, saveAbility: "dex", dmgCount: 10, dmgFaces: 8, dmgType: "火焰", effect: "专注。敏捷豁免。10d8火焰。成功减半。" }),
  p({ id: "preset-maze", name: "迷宫术", level: 8, school: "咒法", duration: "专注，至多 10 分钟", concentration: true, effect: "专注。" }),
  p({ id: "preset-mind-blank", name: "心灵屏障", level: 8, school: "防护", range: "触及", duration: "24 小时", effect: "见规则书。" }),
  p({ id: "preset-power-word-stun", name: "律令震慑", level: 8, school: "惑控", s: false, saveAbility: "con", effect: "体质豁免。" }),
  p({ id: "preset-sunburst", name: "阳炎爆", level: 8, school: "塑能", range: "150 尺", m: true, materials: "a piece of sunstone", saveAbility: "con", dmgCount: 12, dmgType: "光耀", effect: "体质豁免。12d6光耀。成功减半。" }),
  p({ id: "preset-telepathy", name: "心灵感应", level: 8, school: "预言", range: "无限", duration: "24 小时", m: true, materials: "a pair of linked silver rings", effect: "见规则书。" }),
  p({ id: "preset-tsunami", name: "海啸术", level: 8, school: "咒法", castingTime: "1 分钟", range: "1 里", duration: "专注，至多 6 轮", concentration: true, saveAbility: "str", dmgCount: 6, dmgFaces: 10, dmgType: "钝击", effect: "专注。力量豁免。6d10钝击。成功减半。" }),
  p({ id: "preset-astral-projection", name: "星界投影", level: 9, school: "死灵", castingTime: "1 小时", range: "10 尺", duration: "直至解除", m: true, materials: "for each of the spell's targets, one jacinth worth 1,000+ GP and one silver bar worth 100+ GP, all of which the spell consumes", effect: "见规则书。" }),
  p({ id: "preset-foresight", name: "预见术", level: 9, school: "预言", castingTime: "1 分钟", range: "触及", duration: "8 小时", m: true, materials: "a hummingbird feather", effect: "见规则书。" }),
  p({ id: "preset-gate", name: "异界之门", level: 9, school: "咒法", duration: "专注，至多 1 分钟", concentration: true, m: true, materials: "a diamond worth 5,000+ GP", effect: "专注。" }),
  p({ id: "preset-imprisonment", name: "禁锢术", level: 9, school: "防护", castingTime: "1 分钟", range: "30 尺", duration: "直至解除", m: true, materials: "a statuette of the target worth 5,000+ GP", saveAbility: "wis", effect: "感知豁免。" }),
  p({ id: "preset-mass-heal", name: "群体医疗术", level: 9, school: "防护", effect: "见规则书。" }),
  p({ id: "preset-meteor-swarm", name: "流星爆", level: 9, school: "塑能", range: "1 里", saveAbility: "dex", dmgCount: 20, dmgType: "自选", effect: "敏捷豁免。20d6自选。成功减半。" }),
  p({ id: "preset-power-word-heal", name: "律令医疗", level: 9, school: "惑控", effect: "见规则书。" }),
  p({ id: "preset-power-word-kill", name: "律令死亡", level: 9, school: "惑控", s: false, dmgCount: 12, dmgFaces: 12, dmgType: "心灵", effect: "12d12心灵。" }),
  p({ id: "preset-prismatic-wall", name: "虹光法墙", level: 9, school: "防护", duration: "10 分钟", saveAbility: "con", dmgCount: 12, dmgType: "自选", effect: "体质豁免。12d6自选。成功减半。" }),
  p({ id: "preset-shapechange", name: "形体变化", level: 9, school: "变化", range: "自身", duration: "专注，至多 1 小时", concentration: true, m: true, materials: "a jade circlet worth 1,500+ GP", effect: "专注。" }),
  p({ id: "preset-storm-of-vengeance", name: "复仇风暴", level: 9, school: "咒法", range: "1 里", duration: "专注，至多 1 分钟", concentration: true, saveAbility: "con", dmgCount: 2, dmgType: "自选", effect: "专注。体质豁免。2d6自选。成功减半。" }),
  p({ id: "preset-time-stop", name: "时间停止", level: 9, school: "变化", range: "自身", s: false, effect: "见规则书。" }),
  p({ id: "preset-true-polymorph", name: "完全变形术", level: 9, school: "变化", range: "30 尺", duration: "专注，至多 1 小时", concentration: true, m: true, materials: "a drop of mercury, a dollop of gum arabic, and a wisp of smoke", saveAbility: "wis", effect: "专注。感知豁免。" }),
  p({ id: "preset-true-resurrection", name: "完全复生术", level: 9, school: "死灵", castingTime: "1 小时", range: "触及", m: true, materials: "diamonds worth 25,000+ GP, which the spell consumes", effect: "见规则书。" }),
  p({ id: "preset-weird", name: "怪影杀手", level: 9, school: "幻术", range: "120 尺", duration: "专注，至多 1 分钟", concentration: true, saveAbility: "wis", dmgCount: 10, dmgFaces: 10, dmgType: "心灵", effect: "专注。感知豁免。10d10心灵。成功减半。" }),
  p({ id: "preset-wish", name: "祈愿术", level: 9, school: "咒法", range: "自身", s: false, effect: "见规则书。" }),
];

export function spellFromPreset(preset: DndSpellPreset): DndSpellPreset {
  return {
    ...preset,
    id: crypto.randomUUID(),
    prepared: preset.level === 0,
  };
}

export function mergeCoreSpellPresets(existing: DndSpellPreset[]): DndSpellPreset[] {
  const have = new Set(existing.map((p) => p.name.trim()));
  const extra = DEFAULT_SPELL_PRESETS.filter((p) => !have.has(p.name.trim())).map(
    (p) => ({ ...p })
  );
  return extra.length ? [...existing, ...extra] : existing;
}

